/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "auditlog")
public class Auditlog implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Auditlog.class);

    // Raw attributes
    private Integer id;
    private String author;
    private String event;
    private Date eventDate;
    private String stringAttribute1;
    private String stringAttribute2;
    private String stringAttribute3;
    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Auditlog id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [author] ------------------------

    @Size(max = 256)
    @Column(name = "author", length = 256)
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Auditlog author(String author) {
        setAuthor(author);
        return this;
    }
    // -- [event] ------------------------

    @Size(max = 256)
    @Column(name = "event", length = 256)
    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public Auditlog event(String event) {
        setEvent(event);
        return this;
    }
    // -- [eventDate] ------------------------

    @Column(name = "event_date", length = 29)
    @Temporal(TIMESTAMP)
    public Date getEventDate() {
        return eventDate;
    }

    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    public Auditlog eventDate(Date eventDate) {
        setEventDate(eventDate);
        return this;
    }
    // -- [stringAttribute1] ------------------------

    @Size(max = 256)
    @Column(name = "string_attribute_1", length = 256)
    public String getStringAttribute1() {
        return stringAttribute1;
    }

    public void setStringAttribute1(String stringAttribute1) {
        this.stringAttribute1 = stringAttribute1;
    }

    public Auditlog stringAttribute1(String stringAttribute1) {
        setStringAttribute1(stringAttribute1);
        return this;
    }
    // -- [stringAttribute2] ------------------------

    @Size(max = 256)
    @Column(name = "string_attribute_2", length = 256)
    public String getStringAttribute2() {
        return stringAttribute2;
    }

    public void setStringAttribute2(String stringAttribute2) {
        this.stringAttribute2 = stringAttribute2;
    }

    public Auditlog stringAttribute2(String stringAttribute2) {
        setStringAttribute2(stringAttribute2);
        return this;
    }
    // -- [stringAttribute3] ------------------------

    @Size(max = 256)
    @Column(name = "string_attribute_3", length = 256)
    public String getStringAttribute3() {
        return stringAttribute3;
    }

    public void setStringAttribute3(String stringAttribute3) {
        this.stringAttribute3 = stringAttribute3;
    }

    public Auditlog stringAttribute3(String stringAttribute3) {
        setStringAttribute3(stringAttribute3);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Auditlog withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Auditlog && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Auditlog instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("author", getAuthor()) //
                .add("event", getEvent()) //
                .add("eventDate", getEventDate()) //
                .add("stringAttribute1", getStringAttribute1()) //
                .add("stringAttribute2", getStringAttribute2()) //
                .add("stringAttribute3", getStringAttribute3()) //
                .toString();
    }
}