/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Auditlog.class)
public abstract class Auditlog_ {

    // Raw attributes
    public static volatile SingularAttribute<Auditlog, Integer> id;
    public static volatile SingularAttribute<Auditlog, String> author;
    public static volatile SingularAttribute<Auditlog, String> event;
    public static volatile SingularAttribute<Auditlog, Date> eventDate;
    public static volatile SingularAttribute<Auditlog, String> stringAttribute1;
    public static volatile SingularAttribute<Auditlog, String> stringAttribute2;
    public static volatile SingularAttribute<Auditlog, String> stringAttribute3;
}