/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import java.util.Date;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Sgedircci.class)
public abstract class Sgedircci_ {

    // Raw attributes
    public static volatile SingularAttribute<Sgedircci, Integer> id;
    public static volatile SingularAttribute<Sgedircci, String> codeLigne;
    public static volatile SingularAttribute<Sgedircci, String> codeBanque;
    public static volatile SingularAttribute<Sgedircci, String> codeLocalite;
    public static volatile SingularAttribute<Sgedircci, String> numeroGuichet;
    public static volatile SingularAttribute<Sgedircci, String> anneeRcc;
    public static volatile SingularAttribute<Sgedircci, String> moisRcc;
    public static volatile SingularAttribute<Sgedircci, Integer> ncompteCarte;
    public static volatile SingularAttribute<Sgedircci, Integer> rcompteCarte;
    public static volatile SingularAttribute<Sgedircci, Integer> douvertureEmission;
    public static volatile SingularAttribute<Sgedircci, String> dcompteCarte;
    public static volatile SingularAttribute<Sgedircci, String> nomRsociale;
    public static volatile SingularAttribute<Sgedircci, String> numIdentification;
    public static volatile SingularAttribute<Sgedircci, String> centreRc;
    public static volatile SingularAttribute<Sgedircci, String> rc;
    public static volatile SingularAttribute<Sgedircci, String> pays;
    public static volatile SingularAttribute<Sgedircci, String> ville;
    public static volatile SingularAttribute<Sgedircci, String> adresse;
    public static volatile SingularAttribute<Sgedircci, Long> sdebut;
    public static volatile SingularAttribute<Sgedircci, Long> totalMcredit;
    public static volatile SingularAttribute<Sgedircci, Long> totalMdebit;
    public static volatile SingularAttribute<Sgedircci, Long> soldeFmois;
    public static volatile SingularAttribute<Sgedircci, String> champSupp2;
    public static volatile SingularAttribute<Sgedircci, String> champSupp3;
    public static volatile SingularAttribute<Sgedircci, String> champSupp4;
    public static volatile SingularAttribute<Sgedircci, String> champSupp5;
    public static volatile SingularAttribute<Sgedircci, Date> creationDate;
    public static volatile SingularAttribute<Sgedircci, String> creationAuthor;
    public static volatile SingularAttribute<Sgedircci, Date> lastModificationDate;
    public static volatile SingularAttribute<Sgedircci, String> lastModificationAuthor;
    public static volatile SingularAttribute<Sgedircci, String> motif;
    public static volatile SingularAttribute<Sgedircci, String> lib1;
    public static volatile SingularAttribute<Sgedircci, String> lib2;
    public static volatile SingularAttribute<Sgedircci, String> lib3;

    // Many to one
    public static volatile SingularAttribute<Sgedircci, SgediDictodc> qualiteSclient;
    public static volatile SingularAttribute<Sgedircci, Userrole> codeRole;
    public static volatile SingularAttribute<Sgedircci, Sgedixml> idXml;
    public static volatile SingularAttribute<Sgedircci, SgediParams> statutInt;
    public static volatile SingularAttribute<Sgedircci, SgediDictodc> typeIdentification;
    public static volatile SingularAttribute<Sgedircci, SgediParams> statutEch;
    public static volatile SingularAttribute<Sgedircci, SgediParams> codeErr;

    // One to many
    public static volatile ListAttribute<Sgedircci, SgediRccidotation> sgediRccidotations;
    public static volatile ListAttribute<Sgedircci, SgediEdircciMo> sgediEdircciMos;
}