/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static javax.persistence.CascadeType.ALL;
import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.EAGER;
import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.TemporalType.DATE;
import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

import ma.sgma.edi2.audit.AuditContextHolder;

@Entity
@Table(name = "sgedirffi")
public class Sgedirffi implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Sgedirffi.class);

    // Raw attributes
    private Integer id;
    private String codeLigne;
    private String codeBanque;
    private String numeroGuichet;
    private String anneRffi;
    private String moisRffi;
    private String decadeRffi;
    private String bicSwift;
    private String ncp;
    private String nomRsociale;
    private String numIdentification;
    private String centreRc;
    private String rc;
    private String pays;
    private String ville;
    private String adresse;
    private String nomRsocialePartenaire;
    private String paysPartenaire;
    private String codeNoperation;
    private String pprovenanceDestination;
    private String codeDevise;
    private Double montantDevise;
    private Double coursApplique;
    private Double montantApplique;
    private Date dateExecution;
    private String numeroAutorisationOc;
    private String numeroDossier;
    private String informationOperation;
    private String champSupp2;
    private String champSupp3;
    private String champSupp4;
    private String champSupp5;
    private Date creationDate;
    private String creationAuthor;
    private Date lastModificationDate;
    private String lastModificationAuthor;
    private Integer codeErr;
    private String motif;
    private String properties;
    private String valeurErr;
    private String lib1;
    private String lib2;
    private String lib3;
    private String numeroFormule;
    private String client;
    private String codeLocalite;
    private Date dateComptable;
    private String motifoc;
    private String codeerrodc;
    private String affectprofil;
    private Date dateAffect;

    // Many to one
    private Sgedixml idXml;
    private SgediDictodc typeIdentification;
    private SgediParams statutInt;
    private SgediDictodc qualite;
    private Userrole codeRole;
    private SgediDictodc categorieFormule;
    private SgediDictodc sensOperation;
    private SgediParams statutEch;

    // One to many
    private List<SgedirffiErrors> sgedirffiErrorss = new ArrayList<SgedirffiErrors>();
    private List<SgediTitrerffi> sgediTitrerffis = new ArrayList<SgediTitrerffi>();
    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Sgedirffi id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codeLigne] ------------------------

    @Size(max = 50)
    @Column(name = "code_ligne", length = 50)
    public String getCodeLigne() {
        return codeLigne;
    }

    public void setCodeLigne(String codeLigne) {
        this.codeLigne = codeLigne;
    }

    public Sgedirffi codeLigne(String codeLigne) {
        setCodeLigne(codeLigne);
        return this;
    }
    // -- [codeBanque] ------------------------

    @NotEmpty
    @Size(max = 3)
    @Column(name = "code_banque", nullable = false, length = 3)
    public String getCodeBanque() {
        return codeBanque;
    }

    public void setCodeBanque(String codeBanque) {
        this.codeBanque = codeBanque;
    }

    public Sgedirffi codeBanque(String codeBanque) {
        setCodeBanque(codeBanque);
        return this;
    }
    // -- [numeroGuichet] ------------------------

    @NotEmpty
    @Size(max = 7)
    @Column(name = "numero_guichet", nullable = false, length = 7)
    public String getNumeroGuichet() {
        return numeroGuichet;
    }

    public void setNumeroGuichet(String numeroGuichet) {
        this.numeroGuichet = numeroGuichet;
    }

    public Sgedirffi numeroGuichet(String numeroGuichet) {
        setNumeroGuichet(numeroGuichet);
        return this;
    }
    // -- [anneRffi] ------------------------

    @Size(max = 4)
    @Column(name = "anne_rffi", length = 4)
    public String getAnneRffi() {
        return anneRffi;
    }

    public void setAnneRffi(String anneRffi) {
        this.anneRffi = anneRffi;
    }

    public Sgedirffi anneRffi(String anneRffi) {
        setAnneRffi(anneRffi);
        return this;
    }
    // -- [moisRffi] ------------------------

    @Size(max = 2)
    @Column(name = "mois_rffi", length = 2)
    public String getMoisRffi() {
        return moisRffi;
    }

    public void setMoisRffi(String moisRffi) {
        this.moisRffi = moisRffi;
    }

    public Sgedirffi moisRffi(String moisRffi) {
        setMoisRffi(moisRffi);
        return this;
    }
    // -- [decadeRffi] ------------------------

    @Size(max = 2)
    @Column(name = "decade_rffi", length = 2)
    public String getDecadeRffi() {
        return decadeRffi;
    }

    public void setDecadeRffi(String decadeRffi) {
        this.decadeRffi = decadeRffi;
    }

    public Sgedirffi decadeRffi(String decadeRffi) {
        setDecadeRffi(decadeRffi);
        return this;
    }
    // -- [bicSwift] ------------------------

    @Size(max = 11)
    @Column(name = "bic_swift", length = 11)
    public String getBicSwift() {
        return bicSwift;
    }

    public void setBicSwift(String bicSwift) {
        this.bicSwift = bicSwift;
    }

    public Sgedirffi bicSwift(String bicSwift) {
        setBicSwift(bicSwift);
        return this;
    }
    // -- [ncp] ------------------------

    @Size(max = 11)
    @Column(name = "ncp", length = 11)
    public String getNcp() {
        return ncp;
    }

    public void setNcp(String ncp) {
        this.ncp = ncp;
    }

    public Sgedirffi ncp(String ncp) {
        setNcp(ncp);
        return this;
    }
    // -- [nomRsociale] ------------------------

    @Size(max = 200)
    @Column(name = "nom_rsociale", length = 200)
    public String getNomRsociale() {
        return nomRsociale;
    }

    public void setNomRsociale(String nomRsociale) {
        this.nomRsociale = nomRsociale;
    }

    public Sgedirffi nomRsociale(String nomRsociale) {
        setNomRsociale(nomRsociale);
        return this;
    }
    // -- [numIdentification] ------------------------

    @Size(max = 35)
    @Column(name = "num_identification", length = 35)
    public String getNumIdentification() {
        return numIdentification;
    }

    public void setNumIdentification(String numIdentification) {
        this.numIdentification = numIdentification;
    }

    public Sgedirffi numIdentification(String numIdentification) {
        setNumIdentification(numIdentification);
        return this;
    }
    // -- [centreRc] ------------------------

    @Size(max = 3)
    @Column(name = "centre_rc", length = 3)
    public String getCentreRc() {
        return centreRc;
    }

    public void setCentreRc(String centreRc) {
        this.centreRc = centreRc;
    }

    public Sgedirffi centreRc(String centreRc) {
        setCentreRc(centreRc);
        return this;
    }
    // -- [rc] ------------------------

    @Size(max = 100)
    @Column(name = "rc", length = 100)
    public String getRc() {
        return rc;
    }

    public void setRc(String rc) {
        this.rc = rc;
    }

    public Sgedirffi rc(String rc) {
        setRc(rc);
        return this;
    }
    // -- [pays] ------------------------

    @Size(max = 2)
    @Column(name = "pays", length = 2)
    public String getPays() {
        return pays;
    }

    public void setPays(String pays) {
        this.pays = pays;
    }

    public Sgedirffi pays(String pays) {
        setPays(pays);
        return this;
    }
    // -- [ville] ------------------------

    @Size(max = 200)
    @Column(name = "ville", length = 200)
    public String getVille() {
        return ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public Sgedirffi ville(String ville) {
        setVille(ville);
        return this;
    }
    // -- [adresse] ------------------------

    @Size(max = 200)
    @Column(name = "adresse", length = 200)
    public String getAdresse() {
        return adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public Sgedirffi adresse(String adresse) {
        setAdresse(adresse);
        return this;
    }
    // -- [nomRsocialePartenaire] ------------------------

    @Size(max = 200)
    @Column(name = "nom_rsociale_partenaire", length = 200)
    public String getNomRsocialePartenaire() {
        return nomRsocialePartenaire;
    }

    public void setNomRsocialePartenaire(String nomRsocialePartenaire) {
        this.nomRsocialePartenaire = nomRsocialePartenaire;
    }

    public Sgedirffi nomRsocialePartenaire(String nomRsocialePartenaire) {
        setNomRsocialePartenaire(nomRsocialePartenaire);
        return this;
    }
    // -- [paysPartenaire] ------------------------

    @Size(max = 2)
    @Column(name = "pays_partenaire", length = 2)
    public String getPaysPartenaire() {
        return paysPartenaire;
    }

    public void setPaysPartenaire(String paysPartenaire) {
        this.paysPartenaire = paysPartenaire;
    }

    public Sgedirffi paysPartenaire(String paysPartenaire) {
        setPaysPartenaire(paysPartenaire);
        return this;
    }
    // -- [codeNoperation] ------------------------

    @Size(max = 4)
    @Column(name = "code_noperation", length = 4)
    public String getCodeNoperation() {
        return codeNoperation;
    }

    public void setCodeNoperation(String codeNoperation) {
        this.codeNoperation = codeNoperation;
    }

    public Sgedirffi codeNoperation(String codeNoperation) {
        setCodeNoperation(codeNoperation);
        return this;
    }
    // -- [pprovenanceDestination] ------------------------

    @Size(max = 2)
    @Column(name = "pprovenance_destination", length = 2)
    public String getPprovenanceDestination() {
        return pprovenanceDestination;
    }

    public void setPprovenanceDestination(String pprovenanceDestination) {
        this.pprovenanceDestination = pprovenanceDestination;
    }

    public Sgedirffi pprovenanceDestination(String pprovenanceDestination) {
        setPprovenanceDestination(pprovenanceDestination);
        return this;
    }
    // -- [codeDevise] ------------------------

    @Size(max = 3)
    @Column(name = "code_devise", length = 3)
    public String getCodeDevise() {
        return codeDevise;
    }

    public void setCodeDevise(String codeDevise) {
        this.codeDevise = codeDevise;
    }

    public Sgedirffi codeDevise(String codeDevise) {
        setCodeDevise(codeDevise);
        return this;
    }
    // -- [montantDevise] ------------------------

    @Digits(integer = 11, fraction = 6)
    @Column(name = "montant_devise", precision = 11, scale = 7)
    public Double getMontantDevise() {
        return montantDevise;
    }

    public void setMontantDevise(Double montantDevise) {
        this.montantDevise = montantDevise;
    }

    public Sgedirffi montantDevise(Double montantDevise) {
        setMontantDevise(montantDevise);
        return this;
    }
    // -- [coursApplique] ------------------------

    @Digits(integer = 11, fraction = 6)
    @Column(name = "cours_applique", precision = 11, scale = 6)
    public Double getCoursApplique() {
        return coursApplique;
    }

    public void setCoursApplique(Double coursApplique) {
        this.coursApplique = coursApplique;
    }

    public Sgedirffi coursApplique(Double coursApplique) {
        setCoursApplique(coursApplique);
        return this;
    }
    // -- [montantApplique] ------------------------

    @Digits(integer = 13, fraction = 4)
    @Column(name = "montant_applique", precision = 13, scale = 4)
    public Double getMontantApplique() {
        return montantApplique;
    }

    public void setMontantApplique(Double montantApplique) {
        this.montantApplique = montantApplique;
    }

    public Sgedirffi montantApplique(Double montantApplique) {
        setMontantApplique(montantApplique);
        return this;
    }
    // -- [dateExecution] ------------------------

    @Column(name = "date_execution", length = 13)
    @Temporal(DATE)
    public Date getDateExecution() {
        return dateExecution;
    }

    public void setDateExecution(Date dateExecution) {
        this.dateExecution = dateExecution;
    }

    public Sgedirffi dateExecution(Date dateExecution) {
        setDateExecution(dateExecution);
        return this;
    }
    // -- [numeroAutorisationOc] ------------------------

    @Size(max = 20)
    @Column(name = "numero_autorisation_oc", length = 20)
    public String getNumeroAutorisationOc() {
        return numeroAutorisationOc;
    }

    public void setNumeroAutorisationOc(String numeroAutorisationOc) {
        this.numeroAutorisationOc = numeroAutorisationOc;
    }

    public Sgedirffi numeroAutorisationOc(String numeroAutorisationOc) {
        setNumeroAutorisationOc(numeroAutorisationOc);
        return this;
    }
    // -- [numeroDossier] ------------------------

    @Size(max = 30)
    @Column(name = "numero_dossier", length = 30)
    public String getNumeroDossier() {
        return numeroDossier;
    }

    public void setNumeroDossier(String numeroDossier) {
        this.numeroDossier = numeroDossier;
    }

    public Sgedirffi numeroDossier(String numeroDossier) {
        setNumeroDossier(numeroDossier);
        return this;
    }
    // -- [informationOperation] ------------------------

    @Size(max = 400)
    @Column(name = "information_operation", length = 400)
    public String getInformationOperation() {
        return informationOperation;
    }

    public void setInformationOperation(String informationOperation) {
        this.informationOperation = informationOperation;
    }

    public Sgedirffi informationOperation(String informationOperation) {
        setInformationOperation(informationOperation);
        return this;
    }
    // -- [champSupp2] ------------------------

    @Size(max = 400)
    @Column(name = "champ_supp2", length = 400)
    public String getChampSupp2() {
        return champSupp2;
    }

    public void setChampSupp2(String champSupp2) {
        this.champSupp2 = champSupp2;
    }

    public Sgedirffi champSupp2(String champSupp2) {
        setChampSupp2(champSupp2);
        return this;
    }
    // -- [champSupp3] ------------------------

    @Size(max = 400)
    @Column(name = "champ_supp3", length = 400)
    public String getChampSupp3() {
        return champSupp3;
    }

    public void setChampSupp3(String champSupp3) {
        this.champSupp3 = champSupp3;
    }

    public Sgedirffi champSupp3(String champSupp3) {
        setChampSupp3(champSupp3);
        return this;
    }
    // -- [champSupp4] ------------------------

    @Size(max = 400)
    @Column(name = "champ_supp4", length = 400)
    public String getChampSupp4() {
        return champSupp4;
    }

    public void setChampSupp4(String champSupp4) {
        this.champSupp4 = champSupp4;
    }

    public Sgedirffi champSupp4(String champSupp4) {
        setChampSupp4(champSupp4);
        return this;
    }
    // -- [champSupp5] ------------------------

    @Size(max = 400)
    @Column(name = "champ_supp5", length = 400)
    public String getChampSupp5() {
        return champSupp5;
    }

    public void setChampSupp5(String champSupp5) {
        this.champSupp5 = champSupp5;
    }

    public Sgedirffi champSupp5(String champSupp5) {
        setChampSupp5(champSupp5);
        return this;
    }
    // -- [creationDate] ------------------------

    @Column(name = "creation_date", nullable = false, length = 29)
    @Temporal(TIMESTAMP)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Sgedirffi creationDate(Date creationDate) {
        setCreationDate(creationDate);
        return this;
    }
    // -- [creationAuthor] ------------------------

    @Column(name = "creation_author", length = 200)
    public String getCreationAuthor() {
        return creationAuthor;
    }

    public void setCreationAuthor(String creationAuthor) {
        this.creationAuthor = creationAuthor;
    }

    public Sgedirffi creationAuthor(String creationAuthor) {
        setCreationAuthor(creationAuthor);
        return this;
    }
    // -- [lastModificationDate] ------------------------

    @Column(name = "last_modification_date", length = 29)
    @Temporal(TIMESTAMP)
    public Date getLastModificationDate() {
        return lastModificationDate;
    }

    public void setLastModificationDate(Date lastModificationDate) {
        this.lastModificationDate = lastModificationDate;
    }

    public Sgedirffi lastModificationDate(Date lastModificationDate) {
        setLastModificationDate(lastModificationDate);
        return this;
    }
    // -- [lastModificationAuthor] ------------------------

    @Column(name = "last_modification_author", length = 200)
    public String getLastModificationAuthor() {
        return lastModificationAuthor;
    }

    public void setLastModificationAuthor(String lastModificationAuthor) {
        this.lastModificationAuthor = lastModificationAuthor;
    }

    public Sgedirffi lastModificationAuthor(String lastModificationAuthor) {
        setLastModificationAuthor(lastModificationAuthor);
        return this;
    }
    // -- [codeErr] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "code_err", precision = 10)
    public Integer getCodeErr() {
        return codeErr;
    }

    public void setCodeErr(Integer codeErr) {
        this.codeErr = codeErr;
    }

    public Sgedirffi codeErr(Integer codeErr) {
        setCodeErr(codeErr);
        return this;
    }
    // -- [motif] ------------------------

    @Size(max = 400)
    @Column(name = "motif", length = 400)
    public String getMotif() {
        return motif;
    }

    public void setMotif(String motif) {
        this.motif = motif;
    }

    public Sgedirffi motif(String motif) {
        setMotif(motif);
        return this;
    }
    // -- [properties] ------------------------

    @Size(max = 400)
    @Column(name = "properties", length = 400)
    public String getProperties() {
        return properties;
    }

    public void setProperties(String properties) {
        this.properties = properties;
    }

    public Sgedirffi properties(String properties) {
        setProperties(properties);
        return this;
    }
    // -- [valeurErr] ------------------------

    @Size(max = 400)
    @Column(name = "valeur_err", length = 400)
    public String getValeurErr() {
        return valeurErr;
    }

    public void setValeurErr(String valeurErr) {
        this.valeurErr = valeurErr;
    }

    public Sgedirffi valeurErr(String valeurErr) {
        setValeurErr(valeurErr);
        return this;
    }
    // -- [lib1] ------------------------

    @Size(max = 100)
    @Column(name = "lib1", length = 100)
    public String getLib1() {
        return lib1;
    }

    public void setLib1(String lib1) {
        this.lib1 = lib1;
    }

    public Sgedirffi lib1(String lib1) {
        setLib1(lib1);
        return this;
    }
    // -- [lib2] ------------------------

    @Size(max = 100)
    @Column(name = "lib2", length = 100)
    public String getLib2() {
        return lib2;
    }

    public void setLib2(String lib2) {
        this.lib2 = lib2;
    }

    public Sgedirffi lib2(String lib2) {
        setLib2(lib2);
        return this;
    }
    // -- [lib3] ------------------------

    @Size(max = 100)
    @Column(name = "lib3", length = 100)
    public String getLib3() {
        return lib3;
    }

    public void setLib3(String lib3) {
        this.lib3 = lib3;
    }

    public Sgedirffi lib3(String lib3) {
        setLib3(lib3);
        return this;
    }
    // -- [numeroFormule] ------------------------

    @Size(max = 100)
    @Column(name = "numero_formule", length = 100)
    public String getNumeroFormule() {
        return numeroFormule;
    }

    public void setNumeroFormule(String numeroFormule) {
        this.numeroFormule = numeroFormule;
    }

    public Sgedirffi numeroFormule(String numeroFormule) {
        setNumeroFormule(numeroFormule);
        return this;
    }
    // -- [client] ------------------------

    @Size(max = 50)
    @Column(name = "client", length = 50)
    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public Sgedirffi client(String client) {
        setClient(client);
        return this;
    }
    // -- [codeLocalite] ------------------------

    @Size(max = 3)
    @Column(name = "code_localite", length = 3)
    public String getCodeLocalite() {
        return codeLocalite;
    }

    public void setCodeLocalite(String codeLocalite) {
        this.codeLocalite = codeLocalite;
    }

    public Sgedirffi codeLocalite(String codeLocalite) {
        setCodeLocalite(codeLocalite);
        return this;
    }
    // -- [dateComptable] ------------------------

    @Column(name = "date_comptable", length = 13)
    @Temporal(DATE)
    public Date getDateComptable() {
        return dateComptable;
    }

    public void setDateComptable(Date dateComptable) {
        this.dateComptable = dateComptable;
    }

    public Sgedirffi dateComptable(Date dateComptable) {
        setDateComptable(dateComptable);
        return this;
    }
    // -- [motifoc] ------------------------

    @Size(max = 250)
    @Column(name = "motifoc", length = 250)
    public String getMotifoc() {
        return motifoc;
    }

    public void setMotifoc(String motifoc) {
        this.motifoc = motifoc;
    }

    public Sgedirffi motifoc(String motifoc) {
        setMotifoc(motifoc);
        return this;
    }
    // -- [codeerrodc] ------------------------

    @Size(max = 10)
    @Column(name = "codeerrodc", length = 10)
    public String getCodeerrodc() {
        return codeerrodc;
    }

    public void setCodeerrodc(String codeerrodc) {
        this.codeerrodc = codeerrodc;
    }

    public Sgedirffi codeerrodc(String codeerrodc) {
        setCodeerrodc(codeerrodc);
        return this;
    }
    // -- [affectprofil] ------------------------

    @Size(max = 200)
    @Column(name = "affectprofil", length = 200)
    public String getAffectprofil() {
        return affectprofil;
    }

    public void setAffectprofil(String affectprofil) {
        this.affectprofil = affectprofil;
    }

    public Sgedirffi affectprofil(String affectprofil) {
        setAffectprofil(affectprofil);
        return this;
    }
    // -- [dateAffect] ------------------------

    @Column(name = "date_affect", length = 29)
    @Temporal(TIMESTAMP)
    public Date getDateAffect() {
        return dateAffect;
    }

    public void setDateAffect(Date dateAffect) {
        this.dateAffect = dateAffect;
    }

    public Sgedirffi dateAffect(Date dateAffect) {
        setDateAffect(dateAffect);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.idXml ==> Sgedixml.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "id_xml")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public Sgedixml getIdXml() {
        return idXml;
    }

    /**
     * Set the {@link #idXml} without adding this Sgedirffi instance on the passed {@link #idXml}
     */
    public void setIdXml(Sgedixml idXml) {
        this.idXml = idXml;
    }

    public Sgedirffi idXml(Sgedixml idXml) {
        setIdXml(idXml);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.typeIdentification ==> SgediDictodc.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "type_identification")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediDictodc getTypeIdentification() {
        return typeIdentification;
    }

    /**
     * Set the {@link #typeIdentification} without adding this Sgedirffi instance on the passed {@link #typeIdentification}
     */
    public void setTypeIdentification(SgediDictodc typeIdentification) {
        this.typeIdentification = typeIdentification;
    }

    public Sgedirffi typeIdentification(SgediDictodc typeIdentification) {
        setTypeIdentification(typeIdentification);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.statutInt ==> SgediParams.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "statut_int")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediParams getStatutInt() {
        return statutInt;
    }

    /**
     * Set the {@link #statutInt} without adding this Sgedirffi instance on the passed {@link #statutInt}
     */
    public void setStatutInt(SgediParams statutInt) {
        this.statutInt = statutInt;
    }

    public Sgedirffi statutInt(SgediParams statutInt) {
        setStatutInt(statutInt);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.qualite ==> SgediDictodc.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "qualite")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediDictodc getQualite() {
        return qualite;
    }

    /**
     * Set the {@link #qualite} without adding this Sgedirffi instance on the passed {@link #qualite}
     */
    public void setQualite(SgediDictodc qualite) {
        this.qualite = qualite;
    }

    public Sgedirffi qualite(SgediDictodc qualite) {
        setQualite(qualite);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.codeRole ==> Userrole.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "code_role")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public Userrole getCodeRole() {
        return codeRole;
    }

    /**
     * Set the {@link #codeRole} without adding this Sgedirffi instance on the passed {@link #codeRole}
     */
    public void setCodeRole(Userrole codeRole) {
        this.codeRole = codeRole;
    }

    public Sgedirffi codeRole(Userrole codeRole) {
        setCodeRole(codeRole);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.categorieFormule ==> SgediDictodc.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "categorie_formule", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediDictodc getCategorieFormule() {
        return categorieFormule;
    }

    /**
     * Set the {@link #categorieFormule} without adding this Sgedirffi instance on the passed {@link #categorieFormule}
     */
    public void setCategorieFormule(SgediDictodc categorieFormule) {
        this.categorieFormule = categorieFormule;
    }

    public Sgedirffi categorieFormule(SgediDictodc categorieFormule) {
        setCategorieFormule(categorieFormule);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.sensOperation ==> SgediDictodc.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "sens_operation", nullable = false)
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediDictodc getSensOperation() {
        return sensOperation;
    }

    /**
     * Set the {@link #sensOperation} without adding this Sgedirffi instance on the passed {@link #sensOperation}
     */
    public void setSensOperation(SgediDictodc sensOperation) {
        this.sensOperation = sensOperation;
    }

    public Sgedirffi sensOperation(SgediDictodc sensOperation) {
        setSensOperation(sensOperation);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Sgedirffi.statutEch ==> SgediParams.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "statut_ech")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = EAGER)
    public SgediParams getStatutEch() {
        return statutEch;
    }

    /**
     * Set the {@link #statutEch} without adding this Sgedirffi instance on the passed {@link #statutEch}
     */
    public void setStatutEch(SgediParams statutEch) {
        this.statutEch = statutEch;
    }

    public Sgedirffi statutEch(SgediParams statutEch) {
        setStatutEch(statutEch);
        return this;
    }

    // -----------------------------------------------------------------
    // One to Many support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: sgedirffi ==> sgedirffiErrorss
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @OneToMany(mappedBy = "coderffi", orphanRemoval = true, cascade = ALL)
    public List<SgedirffiErrors> getSgedirffiErrorss() {
        return sgedirffiErrorss;
    }

    /**
     * Set the {@link SgedirffiErrors} list.
     * It is recommended to use the helper method {@link #addSgedirffiErrors(SgedirffiErrors)} / {@link #removeSgedirffiErrors(SgedirffiErrors)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param sgedirffiErrorss the list to set
     */
    public void setSgedirffiErrorss(List<SgedirffiErrors> sgedirffiErrorss) {
        this.sgedirffiErrorss = sgedirffiErrorss;
    }

    /**
     * Helper method to add the passed {@link SgedirffiErrors} to the {@link #sgedirffiErrorss} list
     * and set this coderffi on the passed sgedirffiErrors to preserve referential
     * integrity at the object level.
     *
     * @param sgedirffiErrors the to add
     * @return true if the sgedirffiErrors could be added to the sgedirffiErrorss list, false otherwise
     */
    public boolean addSgedirffiErrors(SgedirffiErrors sgedirffiErrors) {
        if (getSgedirffiErrorss().add(sgedirffiErrors)) {
            sgedirffiErrors.setCoderffi(this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to remove the passed {@link SgedirffiErrors} from the {@link #sgedirffiErrorss} list and unset
     * this coderffi from the passed sgedirffiErrors to preserve referential integrity at the object level.
     *
     * @param sgedirffiErrors the instance to remove
     * @return true if the sgedirffiErrors could be removed from the sgedirffiErrorss list, false otherwise
     */
    public boolean removeSgedirffiErrors(SgedirffiErrors sgedirffiErrors) {
        if (getSgedirffiErrorss().remove(sgedirffiErrors)) {
            sgedirffiErrors.setCoderffi(null);
            return true;
        }
        return false;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // one to many: sgedirffi ==> sgediTitrerffis
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @OneToMany(mappedBy = "idrffi" )
    public List<SgediTitrerffi> getSgediTitrerffis() {
        return sgediTitrerffis;
    }

    /**
     * Set the {@link SgediTitrerffi} list.
     * It is recommended to use the helper method {@link #addSgediTitrerffi(SgediTitrerffi)} / {@link #removeSgediTitrerffi(SgediTitrerffi)}
     * if you want to preserve referential integrity at the object level.
     *
     * @param sgediTitrerffis the list to set
     */
    public void setSgediTitrerffis(List<SgediTitrerffi> sgediTitrerffis) {
        this.sgediTitrerffis = sgediTitrerffis;
    }

    /**
     * Helper method to add the passed {@link SgediTitrerffi} to the {@link #sgediTitrerffis} list
     * and set this idrffi on the passed sgediTitrerffi to preserve referential
     * integrity at the object level.
     *
     * @param sgediTitrerffi the to add
     * @return true if the sgediTitrerffi could be added to the sgediTitrerffis list, false otherwise
     */
    public boolean addSgediTitrerffi(SgediTitrerffi sgediTitrerffi) {
        if (getSgediTitrerffis().add(sgediTitrerffi)) {
            sgediTitrerffi.setIdrffi(this);
            return true;
        }
        return false;
    }

    /**
     * Helper method to remove the passed {@link SgediTitrerffi} from the {@link #sgediTitrerffis} list and unset
     * this idrffi from the passed sgediTitrerffi to preserve referential integrity at the object level.
     *
     * @param sgediTitrerffi the instance to remove
     * @return true if the sgediTitrerffi could be removed from the sgediTitrerffis list, false otherwise
     */
    public boolean removeSgediTitrerffi(SgediTitrerffi sgediTitrerffi) {
        if (getSgediTitrerffis().remove(sgediTitrerffi)) {
            sgediTitrerffi.setIdrffi(null);
            return true;
        }
        return false;
    }

    /**
     * Apply the default values.
     */
    public Sgedirffi withDefaults() {
        setLastModificationDate(new Date());
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Sgedirffi && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Sgedirffi instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codeLigne", getCodeLigne()) //
                .add("codeBanque", getCodeBanque()) //
                .add("numeroGuichet", getNumeroGuichet()) //
                .add("anneRffi", getAnneRffi()) //
                .add("moisRffi", getMoisRffi()) //
                .add("decadeRffi", getDecadeRffi()) //
                .add("bicSwift", getBicSwift()) //
                .add("ncp", getNcp()) //
                .add("nomRsociale", getNomRsociale()) //
                .add("numIdentification", getNumIdentification()) //
                .add("centreRc", getCentreRc()) //
                .add("rc", getRc()) //
                .add("pays", getPays()) //
                .add("ville", getVille()) //
                .add("adresse", getAdresse()) //
                .add("nomRsocialePartenaire", getNomRsocialePartenaire()) //
                .add("paysPartenaire", getPaysPartenaire()) //
                .add("codeNoperation", getCodeNoperation()) //
                .add("pprovenanceDestination", getPprovenanceDestination()) //
                .add("codeDevise", getCodeDevise()) //
                .add("montantDevise", getMontantDevise()) //
                .add("coursApplique", getCoursApplique()) //
                .add("montantApplique", getMontantApplique()) //
                .add("dateExecution", getDateExecution()) //
                .add("numeroAutorisationOc", getNumeroAutorisationOc()) //
                .add("numeroDossier", getNumeroDossier()) //
                .add("informationOperation", getInformationOperation()) //
                .add("champSupp2", getChampSupp2()) //
                .add("champSupp3", getChampSupp3()) //
                .add("champSupp4", getChampSupp4()) //
                .add("champSupp5", getChampSupp5()) //
                .add("creationDate", getCreationDate()) //
                .add("creationAuthor", getCreationAuthor()) //
                .add("lastModificationDate", getLastModificationDate()) //
                .add("lastModificationAuthor", getLastModificationAuthor()) //
                .add("codeErr", getCodeErr()) //
                .add("motif", getMotif()) //
                .add("properties", getProperties()) //
                .add("valeurErr", getValeurErr()) //
                .add("lib1", getLib1()) //
                .add("lib2", getLib2()) //
                .add("lib3", getLib3()) //
                .add("numeroFormule", getNumeroFormule()) //
                .add("client", getClient()) //
                .add("codeLocalite", getCodeLocalite()) //
                .add("dateComptable", getDateComptable()) //
                .add("motifoc", getMotifoc()) //
                .add("codeerrodc", getCodeerrodc()) //
                .add("affectprofil", getAffectprofil()) //
                .add("dateAffect", getDateAffect()) //
                .toString();
    }

    @PrePersist
    protected void prePersist() {
        if (AuditContextHolder.audit()) {
            setCreationAuthor(AuditContextHolder.username());
            setCreationDate(new Date());
        }
    }

    @PreUpdate
    protected void preUpdate() {
        if (AuditContextHolder.audit()) {
            setLastModificationAuthor(AuditContextHolder.username());
            setLastModificationDate(new Date());
        }
    }
}