/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.FetchType.LAZY;
import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "sgedirffi_errors")
public class SgedirffiErrors implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(SgedirffiErrors.class);

    // Raw attributes
    private Integer id;
    private String propriete;
    private String motif;
    private String valueError;

    // Many to one
    private Sgedirffi coderffi;
    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public SgedirffiErrors id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [propriete] ------------------------

    @Size(max = 400)
    @Column(name = "propriete", length = 400)
    public String getPropriete() {
        return propriete;
    }

    public void setPropriete(String propriete) {
        this.propriete = propriete;
    }

    public SgedirffiErrors propriete(String propriete) {
        setPropriete(propriete);
        return this;
    }
    // -- [motif] ------------------------

    @Size(max = 400)
    @Column(name = "motif", length = 400)
    public String getMotif() {
        return motif;
    }

    public void setMotif(String motif) {
        this.motif = motif;
    }

    public SgedirffiErrors motif(String motif) {
        setMotif(motif);
        return this;
    }
    // -- [valueError] ------------------------

    @Size(max = 400)
    @Column(name = "value_error", length = 400)
    public String getValueError() {
        return valueError;
    }

    public void setValueError(String valueError) {
        this.valueError = valueError;
    }

    public SgedirffiErrors valueError(String valueError) {
        setValueError(valueError);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: SgedirffiErrors.coderffi ==> Sgedirffi.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @JoinColumn(name = "coderffi")
    @ManyToOne(cascade = { PERSIST, MERGE }, fetch = LAZY)
    public Sgedirffi getCoderffi() {
        return coderffi;
    }

    /**
     * Set the {@link #coderffi} without adding this SgedirffiErrors instance on the passed {@link #coderffi}
     * If you want to preserve referential integrity we recommend to use
     * instead the corresponding adder method provided by {@link Sgedirffi}
     */
    public void setCoderffi(Sgedirffi coderffi) {
        this.coderffi = coderffi;
    }

    public SgedirffiErrors coderffi(Sgedirffi coderffi) {
        setCoderffi(coderffi);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SgedirffiErrors withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SgedirffiErrors && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this SgedirffiErrors instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("propriete", getPropriete()) //
                .add("motif", getMotif()) //
                .add("valueError", getValueError()) //
                .toString();
    }
}