/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import java.util.Date;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Sgedirffi.class)
public abstract class Sgedirffi_ {

    // Raw attributes
    public static volatile SingularAttribute<Sgedirffi, Integer> id;
    public static volatile SingularAttribute<Sgedirffi, String> codeLigne;
    public static volatile SingularAttribute<Sgedirffi, String> codeBanque;
    public static volatile SingularAttribute<Sgedirffi, String> numeroGuichet;
    public static volatile SingularAttribute<Sgedirffi, String> anneRffi;
    public static volatile SingularAttribute<Sgedirffi, String> moisRffi;
    public static volatile SingularAttribute<Sgedirffi, String> decadeRffi;
    public static volatile SingularAttribute<Sgedirffi, String> bicSwift;
    public static volatile SingularAttribute<Sgedirffi, String> ncp;
    public static volatile SingularAttribute<Sgedirffi, String> nomRsociale;
    public static volatile SingularAttribute<Sgedirffi, String> numIdentification;
    public static volatile SingularAttribute<Sgedirffi, String> centreRc;
    public static volatile SingularAttribute<Sgedirffi, String> rc;
    public static volatile SingularAttribute<Sgedirffi, String> pays;
    public static volatile SingularAttribute<Sgedirffi, String> ville;
    public static volatile SingularAttribute<Sgedirffi, String> adresse;
    public static volatile SingularAttribute<Sgedirffi, String> nomRsocialePartenaire;
    public static volatile SingularAttribute<Sgedirffi, String> paysPartenaire;
    public static volatile SingularAttribute<Sgedirffi, String> codeNoperation;
    public static volatile SingularAttribute<Sgedirffi, String> pprovenanceDestination;
    public static volatile SingularAttribute<Sgedirffi, String> codeDevise;
    public static volatile SingularAttribute<Sgedirffi, Double> montantDevise;
    public static volatile SingularAttribute<Sgedirffi, Double> coursApplique;
    public static volatile SingularAttribute<Sgedirffi, Double> montantApplique;
    public static volatile SingularAttribute<Sgedirffi, Date> dateExecution;
    public static volatile SingularAttribute<Sgedirffi, String> numeroAutorisationOc;
    public static volatile SingularAttribute<Sgedirffi, String> numeroDossier;
    public static volatile SingularAttribute<Sgedirffi, String> informationOperation;
    public static volatile SingularAttribute<Sgedirffi, String> champSupp2;
    public static volatile SingularAttribute<Sgedirffi, String> champSupp3;
    public static volatile SingularAttribute<Sgedirffi, String> champSupp4;
    public static volatile SingularAttribute<Sgedirffi, String> champSupp5;
    public static volatile SingularAttribute<Sgedirffi, Date> creationDate;
    public static volatile SingularAttribute<Sgedirffi, String> creationAuthor;
    public static volatile SingularAttribute<Sgedirffi, Date> lastModificationDate;
    public static volatile SingularAttribute<Sgedirffi, String> lastModificationAuthor;
    public static volatile SingularAttribute<Sgedirffi, Integer> codeErr;
    public static volatile SingularAttribute<Sgedirffi, String> motif;
    public static volatile SingularAttribute<Sgedirffi, String> properties;
    public static volatile SingularAttribute<Sgedirffi, String> valeurErr;
    public static volatile SingularAttribute<Sgedirffi, String> lib1;
    public static volatile SingularAttribute<Sgedirffi, String> lib2;
    public static volatile SingularAttribute<Sgedirffi, String> lib3;
    public static volatile SingularAttribute<Sgedirffi, String> numeroFormule;
    public static volatile SingularAttribute<Sgedirffi, String> client;
    public static volatile SingularAttribute<Sgedirffi, String> codeLocalite;
    public static volatile SingularAttribute<Sgedirffi, Date> dateComptable;
    public static volatile SingularAttribute<Sgedirffi, String> motifoc;
    public static volatile SingularAttribute<Sgedirffi, String> codeerrodc;
    public static volatile SingularAttribute<Sgedirffi, String> affectprofil;
    public static volatile SingularAttribute<Sgedirffi, Date> dateAffect;

    // Many to one
    public static volatile SingularAttribute<Sgedirffi, Sgedixml> idXml;
    public static volatile SingularAttribute<Sgedirffi, SgediDictodc> typeIdentification;
    public static volatile SingularAttribute<Sgedirffi, SgediParams> statutInt;
    public static volatile SingularAttribute<Sgedirffi, SgediDictodc> qualite;
    public static volatile SingularAttribute<Sgedirffi, Userrole> codeRole;
    public static volatile SingularAttribute<Sgedirffi, SgediDictodc> categorieFormule;
    public static volatile SingularAttribute<Sgedirffi, SgediDictodc> sensOperation;
    public static volatile SingularAttribute<Sgedirffi, SgediParams> statutEch;

    // One to many
    public static volatile ListAttribute<Sgedirffi, SgedirffiErrors> sgedirffiErrorss;
    public static volatile ListAttribute<Sgedirffi, SgediTitrerffi> sgediTitrerffis;
}