/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SgediParams.class)
public abstract class SgediParams_ {

    // Raw attributes
    public static volatile SingularAttribute<SgediParams, Integer> id;
    public static volatile SingularAttribute<SgediParams, String> code;
    public static volatile SingularAttribute<SgediParams, String> libelle;
    public static volatile SingularAttribute<SgediParams, String> lib1;
    public static volatile SingularAttribute<SgediParams, String> lib2;
    public static volatile SingularAttribute<SgediParams, String> lib3;
}