/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static javax.persistence.GenerationType.IDENTITY;
import static javax.persistence.TemporalType.TIMESTAMP;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "sgedixml")
public class Sgedixml implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Sgedixml.class);

    // Raw attributes
    private Integer id;
    private String xml;
    private Integer sens;
    private String typ;
    private Integer anne;
    private Integer mois;
    private Integer decade;
    private Date dateGen;
    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Sgedixml id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [xml] ------------------------

    @NotEmpty
    @Size(max = 200)
    @Column(name = "xml", nullable = false, length = 200)
    public String getXml() {
        return xml;
    }

    public void setXml(String xml) {
        this.xml = xml;
    }

    public Sgedixml xml(String xml) {
        setXml(xml);
        return this;
    }
    // -- [sens] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "sens", nullable = false, precision = 10)
    public Integer getSens() {
        return sens;
    }

    public void setSens(Integer sens) {
        this.sens = sens;
    }

    public Sgedixml sens(Integer sens) {
        setSens(sens);
        return this;
    }
    // -- [typ] ------------------------

    @NotEmpty
    @Size(max = 4)
    @Column(name = "typ", nullable = false, length = 4)
    public String getTyp() {
        return typ;
    }

    public void setTyp(String typ) {
        this.typ = typ;
    }

    public Sgedixml typ(String typ) {
        setTyp(typ);
        return this;
    }
    // -- [anne] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "anne", nullable = false, precision = 10)
    public Integer getAnne() {
        return anne;
    }

    public void setAnne(Integer anne) {
        this.anne = anne;
    }

    public Sgedixml anne(Integer anne) {
        setAnne(anne);
        return this;
    }
    // -- [mois] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "mois", nullable = false, precision = 10)
    public Integer getMois() {
        return mois;
    }

    public void setMois(Integer mois) {
        this.mois = mois;
    }

    public Sgedixml mois(Integer mois) {
        setMois(mois);
        return this;
    }
    // -- [decade] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "decade", nullable = false, precision = 10)
    public Integer getDecade() {
        return decade;
    }

    public void setDecade(Integer decade) {
        this.decade = decade;
    }

    public Sgedixml decade(Integer decade) {
        setDecade(decade);
        return this;
    }
    // -- [dateGen] ------------------------

    @NotNull
    @Column(name = "date_gen", nullable = false, length = 29)
    @Temporal(TIMESTAMP)
    public Date getDateGen() {
        return dateGen;
    }

    public void setDateGen(Date dateGen) {
        this.dateGen = dateGen;
    }

    public Sgedixml dateGen(Date dateGen) {
        setDateGen(dateGen);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Sgedixml withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Sgedixml && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Sgedixml instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("xml", getXml()) //
                .add("sens", getSens()) //
                .add("typ", getTyp()) //
                .add("anne", getAnne()) //
                .add("mois", getMois()) //
                .add("decade", getDecade()) //
                .add("dateGen", getDateGen()) //
                .toString();
    }
}