/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SgediTitrerffi.class)
public abstract class SgediTitrerffi_ {

    // Raw attributes
    public static volatile SingularAttribute<SgediTitrerffi, Integer> id;
    public static volatile SingularAttribute<SgediTitrerffi, String> titre;

    // Many to one
    public static volatile SingularAttribute<SgediTitrerffi, Sgedirffi> idrffi;
}