/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.domain.Sgedirffi_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Sgedirffi} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgedirffiPrinter extends GenericPrinter<Sgedirffi> {
    public SgedirffiPrinter() {
        super(Sgedirffi.class, Sgedirffi_.codeBanque, Sgedirffi_.numeroGuichet);
    }

    @Override
    public String print(Sgedirffi sgedirffi, Locale locale) {
        if (sgedirffi == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgedirffi.getCodeBanque());
        appendIfNotEmpty(ret, sgedirffi.getNumeroGuichet());
        return ret.toString();
    }
}