/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgedirffiErrors;
import ma.sgma.edi2.domain.SgedirffiErrors_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SgedirffiErrors} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgedirffiErrorsPrinter extends GenericPrinter<SgedirffiErrors> {
    public SgedirffiErrorsPrinter() {
        super(SgedirffiErrors.class, SgedirffiErrors_.propriete, SgedirffiErrors_.motif, SgedirffiErrors_.valueError);
    }

    @Override
    public String print(SgedirffiErrors sgedirffiErrors, Locale locale) {
        if (sgedirffiErrors == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgedirffiErrors.getPropriete());
        appendIfNotEmpty(ret, sgedirffiErrors.getMotif());
        appendIfNotEmpty(ret, sgedirffiErrors.getValueError());
        return ret.toString();
    }
}