/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediTitrerffi;
import ma.sgma.edi2.domain.SgediTitrerffi_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SgediTitrerffi} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgediTitrerffiPrinter extends GenericPrinter<SgediTitrerffi> {
    public SgediTitrerffiPrinter() {
        super(SgediTitrerffi.class, SgediTitrerffi_.titre);
    }

    @Override
    public String print(SgediTitrerffi sgediTitrerffi, Locale locale) {
        if (sgediTitrerffi == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgediTitrerffi.getTitre());
        return ret.toString();
    }
}