/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediDictodc;
import ma.sgma.edi2.domain.SgediDictodc_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SgediDictodc} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgediDictodcPrinter extends GenericPrinter<SgediDictodc> {
    public SgediDictodcPrinter() {
        super(SgediDictodc.class, SgediDictodc_.libelle);
    }

    @Override
    public String print(SgediDictodc sgediDictodc, Locale locale) {
        if (sgediDictodc == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgediDictodc.getLibelle());
        return ret.toString();
    }
}