/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.domain.Sgedircci_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Sgedircci} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgedircciPrinter extends GenericPrinter<Sgedircci> {
    public SgedircciPrinter() {
        super(Sgedircci.class, Sgedircci_.codeLigne, Sgedircci_.codeBanque, Sgedircci_.codeLocalite);
    }

    @Override
    public String print(Sgedircci sgedircci, Locale locale) {
        if (sgedircci == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgedircci.getCodeLigne());
        appendIfNotEmpty(ret, sgedircci.getCodeBanque());
        appendIfNotEmpty(ret, sgedircci.getCodeLocalite());
        return ret.toString();
    }
}