/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.domain.Sgedixml_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Sgedixml} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgedixmlPrinter extends GenericPrinter<Sgedixml> {
    public SgedixmlPrinter() {
        super(Sgedixml.class, Sgedixml_.xml, Sgedixml_.typ);
    }

    @Override
    public String print(Sgedixml sgedixml, Locale locale) {
        if (sgedixml == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgedixml.getXml());
        appendIfNotEmpty(ret, sgedixml.getTyp());
        return ret.toString();
    }
}