/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediRccidotation;
import ma.sgma.edi2.domain.SgediRccidotation_;
import ma.sgma.edi2.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link SgediRccidotation} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class SgediRccidotationPrinter extends GenericPrinter<SgediRccidotation> {
    public SgediRccidotationPrinter() {
        super(SgediRccidotation.class, SgediRccidotation_.dottyp);
    }

    @Override
    public String print(SgediRccidotation sgediRccidotation, Locale locale) {
        if (sgediRccidotation == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, sgediRccidotation.getDottyp());
        return ret.toString();
    }
}