/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for Account
 */
@SuppressWarnings("unused")
public class AccountTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Account model = new Account();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Account model = new Account();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Pure Many to Many
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void manyToMany_addSecurityRole() {
        Account many1 = new Account();
        Userrole many2 = new Userrole();

        // add it
        many1.addSecurityRole(many2);

        // check it is propagated
        assertThat(many1.getSecurityRoles()).contains(many2);
        // now let's remove it
        many1.removeSecurityRole(many2);

        // check it is propagated
        assertThat(many1.getSecurityRoles().contains(many2)).isFalse();
    }

    /*
    public void equalsUsingPk() {
        Account model1 = new Account();
        Account model2 = new Account();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setUsername("aaaa");
        model2.setUsername("aaaa");
    
        model1.setPassword("a");
        model2.setPassword("a");
    
        model1.setIsEnabled(true);
        model2.setIsEnabled(true);
    
        model1.setLastConnection(new Date());
        model2.setLastConnection(new Date());
    
        model1.setMdpExpiration(new Date());
        model2.setMdpExpiration(new Date());
    
        model1.setEmail("dummy@dummy.com");
        model2.setEmail("dummy@dummy.com");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}