/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for Auditlog
 */
@SuppressWarnings("unused")
public class AuditlogTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Auditlog model = new Auditlog();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Auditlog model = new Auditlog();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
    public void equalsUsingPk() {
        Auditlog model1 = new Auditlog();
        Auditlog model2 = new Auditlog();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setAuthor("a");
        model2.setAuthor("a");
    
        model1.setEvent("a");
        model2.setEvent("a");
    
        model1.setEventDate(new Date());
        model2.setEventDate(new Date());
    
        model1.setStringAttribute1("a");
        model2.setStringAttribute1("a");
    
        model1.setStringAttribute2("a");
        model2.setStringAttribute2("a");
    
        model1.setStringAttribute3("a");
        model2.setStringAttribute3("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}