/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for SgedirffiErrors
 */
@SuppressWarnings("unused")
public class SgedirffiErrorsTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SgedirffiErrors model = new SgedirffiErrors();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SgedirffiErrors model = new SgedirffiErrors();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  SgedirffiErrors.coderffi ==> Sgedirffi.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setCoderffi() {
        SgedirffiErrors many = new SgedirffiErrors();

        // init
        Sgedirffi one = new Sgedirffi();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setCoderffi(one);

        // make sure it is propagated properly
        assertThat(many.getCoderffi()).isEqualTo(one);

        // now set it to back to null
        many.setCoderffi(null);

        // make sure null is propagated properly
        assertThat(many.getCoderffi()).isNull();
    }

    /*
    public void equalsUsingPk() {
        SgedirffiErrors model1 = new SgedirffiErrors();
        SgedirffiErrors model2 = new SgedirffiErrors();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setPropriete("a");
        model2.setPropriete("a");
    
        model1.setMotif("a");
        model2.setMotif("a");
    
        model1.setValueError("a");
        model2.setValueError("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}