/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for SgediEdircciMo
 */
@SuppressWarnings("unused")
public class SgediEdircciMoTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SgediEdircciMo model = new SgediEdircciMo();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SgediEdircciMo model = new SgediEdircciMo();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  SgediEdircciMo.idrcci ==> Sgedircci.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setIdrcci() {
        SgediEdircciMo many = new SgediEdircciMo();

        // init
        Sgedircci one = new Sgedircci();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setIdrcci(one);

        // make sure it is propagated properly
        assertThat(many.getIdrcci()).isEqualTo(one);

        // now set it to back to null
        many.setIdrcci(null);

        // make sure null is propagated properly
        assertThat(many.getIdrcci()).isNull();
    }

    /*
    public void equalsUsingPk() {
        SgediEdircciMo model1 = new SgediEdircciMo();
        SgediEdircciMo model2 = new SgediEdircciMo();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setMouvrage("a");
        model2.setMouvrage("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}