/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for SgediParams
 */
@SuppressWarnings("unused")
public class SgediParamsTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SgediParams model = new SgediParams();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SgediParams model = new SgediParams();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
    public void equalsUsingPk() {
        SgediParams model1 = new SgediParams();
        SgediParams model2 = new SgediParams();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setCode("a");
        model2.setCode("a");
    
        model1.setLibelle("a");
        model2.setLibelle("a");
    
        model1.setLib1("a");
        model2.setLib1("a");
    
        model1.setLib2("a");
        model2.setLib2("a");
    
        model1.setLib3("a");
        model2.setLib3("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}