/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for SgediTitrerffi
 */
@SuppressWarnings("unused")
public class SgediTitrerffiTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        SgediTitrerffi model = new SgediTitrerffi();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        SgediTitrerffi model = new SgediTitrerffi();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  SgediTitrerffi.idrffi ==> Sgedirffi.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setIdrffi() {
        SgediTitrerffi many = new SgediTitrerffi();

        // init
        Sgedirffi one = new Sgedirffi();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setIdrffi(one);

        // make sure it is propagated properly
        assertThat(many.getIdrffi()).isEqualTo(one);

        // now set it to back to null
        many.setIdrffi(null);

        // make sure null is propagated properly
        assertThat(many.getIdrffi()).isNull();
    }

    /*
    public void equalsUsingPk() {
        SgediTitrerffi model1 = new SgediTitrerffi();
        SgediTitrerffi model2 = new SgediTitrerffi();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setTitre("a");
        model2.setTitre("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}