/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import ma.sgma.edi2.util.ValueGenerator;

/**
 * Basic tests for Sgedixml
 */
@SuppressWarnings("unused")
public class SgedixmlTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Sgedixml model = new Sgedixml();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Sgedixml model = new Sgedixml();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
    public void equalsUsingPk() {
        Sgedixml model1 = new Sgedixml();
        Sgedixml model2 = new Sgedixml();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setXml("a");
        model2.setXml("a");
    
        model1.setSens(1);
        model2.setSens(1);
    
        model1.setTyp("a");
        model2.setTyp("a");
    
        model1.setAnne(1);
        model2.setAnne(1);
    
        model1.setMois(1);
        model2.setMois(1);
    
        model1.setDecade(1);
        model2.setDecade(1);
    
        model1.setDateGen(new Date());
        model2.setDateGen(new Date());
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}