/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Auditlog;
import ma.sgma.edi2.repository.AuditlogRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Auditlog}.
 */
@Named
@ConversationContextScoped
public class AuditlogEditForm extends GenericEditForm<Auditlog, Integer> {
    @Inject
    protected AuditlogController auditlogController;

    @Inject
    public AuditlogEditForm(AuditlogRepository auditlogRepository) {
        super(auditlogRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Auditlog getAuditlog() {
        return getEntity();
    }

    public String print() {
        return auditlogController.print(getAuditlog());
    }
}
