/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Auditlog;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Auditlog} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class AuditlogExcelExporter extends GenericExcelExporter<Auditlog> {
    @Inject
    protected AuditlogSearchForm sf;

    public AuditlogExcelExporter() {
        super("auditlog_author", "auditlog_event", "auditlog_eventDate", "auditlog_stringAttribute1", "auditlog_stringAttribute2", "auditlog_stringAttribute3");
    }

    @Override
    protected void fillResultItem(int row, Auditlog item) {
        int col = 0;
        setValue(row, col++, item.getAuthor());
        setValue(row, col++, item.getEvent());
        setDateTime(row, col++, item.getEventDate());
        setValue(row, col++, item.getStringAttribute1());
        setValue(row, col++, item.getStringAttribute2());
        setValue(row, col++, item.getStringAttribute3());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "auditlog_author", sf.getAuthorSelector());
        setSelector(row++, 0, "auditlog_event", sf.getEventSelector());
        setRangeDateTime(row++, 0, "auditlog_eventDate", sf.getEventDateRange());
        setSelector(row++, 0, "auditlog_stringAttribute1", sf.getStringAttribute1Selector());
        setSelector(row++, 0, "auditlog_stringAttribute2", sf.getStringAttribute2Selector());
        setSelector(row++, 0, "auditlog_stringAttribute3", sf.getStringAttribute3Selector());
    }
}