/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/FileDownload.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import org.primefaces.model.StreamedContent;

import ma.sgma.edi2.domain.SavedSearch;
import ma.sgma.edi2.domain.SavedSearch_;
import ma.sgma.edi2.repository.SavedSearchRepository;
import ma.sgma.edi2.web.domain.support.ByteArrayStreamedContent;

/**
 * Stateless controller to download {@link SavedSearch} binaries 
 */
@Named
@Singleton
public class SavedSearchFileDownload {
    @Inject
    private SavedSearchRepository savedSearchRepository;

    /**
     * Primefaces support for formContent file download.
     */
    public StreamedContent getFormContentStream(final SavedSearch savedSearch) {
        // check whether the binary is null WITHOUT downloading it.
        if (savedSearch.isIdSet()) {
            if (savedSearchRepository.isPropertyNull(savedSearch.getId(), SavedSearch_.formContent)) {
                return null;
            }
        } else if (savedSearch.getFormContent() == null) {
            return null;
        }

        ByteArrayStreamedContent basc = new ByteArrayStreamedContent() {
            @Override
            public byte[] getByteArray() {
                return savedSearchRepository.getFormContent(savedSearch);
            }
        };
        basc.setName("formContent");
        return basc;
    }
}