/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Account;
import ma.sgma.edi2.domain.SavedSearch;
import ma.sgma.edi2.domain.SavedSearch_;
import ma.sgma.edi2.repository.SavedSearchRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.domain.support.GenericToOneAssociation;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SavedSearch}.
 */
@Named
@ConversationContextScoped
public class SavedSearchEditForm extends GenericEditForm<SavedSearch, Integer> {
    @Inject
    protected SavedSearchController savedSearchController;
    @Inject
    protected AccountController accountController;
    protected GenericToOneAssociation<Account, Integer> account;

    @Inject
    public SavedSearchEditForm(SavedSearchRepository savedSearchRepository, SavedSearchGraphLoader savedSearchGraphLoader) {
        super(savedSearchRepository, savedSearchGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SavedSearch getSavedSearch() {
        return getEntity();
    }

    public String print() {
        return savedSearchController.print(getSavedSearch());
    }

    @PostConstruct
    void setupAccountActions() {
        account = new GenericToOneAssociation<Account, Integer>(accountController, SavedSearch_.account) {
            @Override
            protected Account get() {
                return getSavedSearch().getAccount();
            }

            @Override
            protected void set(Account account) {
                getSavedSearch().setAccount(account);
            }
        };
    }

    public GenericToOneAssociation<Account, Integer> getAccount() {
        return account;
    }
}
