/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SavedSearch;
import ma.sgma.edi2.printer.SavedSearchPrinter;
import ma.sgma.edi2.repository.SavedSearchRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SavedSearchPermission;

/**
 * Stateless controller for {@link SavedSearch} conversation start.
 */
@Named
@Singleton
public class SavedSearchController extends GenericController<SavedSearch, Integer> {
    public static final String SAVEDSEARCH_EDIT_URI = "/domain/savedSearchEdit.faces";
    public static final String SAVEDSEARCH_SELECT_URI = "/domain/savedSearchSelect.faces";

    @Inject
    public SavedSearchController(SavedSearchRepository savedSearchRepository, SavedSearchPermission savedSearchPermission,
            SavedSearchPrinter savedSearchPrinter) {
        super(savedSearchRepository, savedSearchPermission, savedSearchPrinter, SAVEDSEARCH_SELECT_URI, SAVEDSEARCH_EDIT_URI);
    }

    public SavedSearchFileUpload getSavedSearchFileUpload(SavedSearch savedSearch) {
        return new SavedSearchFileUpload(savedSearch);
    }
}