/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.SgediParams;
import ma.sgma.edi2.repository.SgediParamsRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SgediParams}.
 */
@Named
@ConversationContextScoped
public class SgediParamsEditForm extends GenericEditForm<SgediParams, Integer> {
    @Inject
    protected SgediParamsController sgediParamsController;

    @Inject
    public SgediParamsEditForm(SgediParamsRepository sgediParamsRepository) {
        super(sgediParamsRepository);
    }

    /**
     * The entity to edit/view.
     */
    public SgediParams getSgediParams() {
        return getEntity();
    }

    public String print() {
        return sgediParamsController.print(getSgediParams());
    }
}
