/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.EntityGraphLoader;

import ma.sgma.edi2.domain.SgediRccidotation;
import ma.sgma.edi2.repository.SgediRccidotationRepository;

/**
 * Preloads the {@link SgediRccidotation} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class SgediRccidotationGraphLoader extends EntityGraphLoader<SgediRccidotation, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected SgediRccidotationGraphLoader() {
        super();
    }

    @Inject
    public SgediRccidotationGraphLoader(SgediRccidotationRepository sgediRccidotationRepository) {
        super(sgediRccidotationRepository);
    }

    @Override
    public void loadGraph(SgediRccidotation sgediRccidotation) {
        loadSingular(sgediRccidotation.getIdrcci());
    }
}