/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;
import static com.jaxio.jpa.querybyexample.Range.newRange;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.Range;
import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgediRccidotation;
import ma.sgma.edi2.domain.SgediRccidotation_;
import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.web.domain.support.GenericSearchForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link SgediRccidotation}.
 * It exposes a {@link SgediRccidotation} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SgediRccidotationSearchForm extends GenericSearchForm<SgediRccidotation, Integer, SgediRccidotationSearchForm> {
    private static final long serialVersionUID = 1L;
    protected SgediRccidotation sgediRccidotation = new SgediRccidotation();
    protected Range<SgediRccidotation, Integer> dottypRange = newRange(SgediRccidotation_.dottyp);
    protected PropertySelector<SgediRccidotation, Integer> dottypSelector = newPropertySelector(SgediRccidotation_.dottyp);
    protected PropertySelector<SgediRccidotation, Sgedircci> idrcciSelector = newPropertySelector(SgediRccidotation_.idrcci);

    public SgediRccidotation getSgediRccidotation() {
        return sgediRccidotation;
    }

    @Override
    protected SgediRccidotation getEntity() {
        return getSgediRccidotation();
    }

    @Override
    public SgediRccidotationSearchForm newInstance() {
        return new SgediRccidotationSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.fetch(SgediRccidotation_.idrcci);
        sp.range(dottypRange);
        sp.property(dottypSelector);
        sp.property(idrcciSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SgediRccidotationSearchForm other) {
        this.sgediRccidotation = other.getSgediRccidotation();
        this.dottypRange = other.getDottypRange();
        this.dottypSelector = other.getDottypSelector();
        this.idrcciSelector = other.getIdrcciSelector();
    }

    // Ranges
    public Range<SgediRccidotation, Integer> getDottypRange() {
        return dottypRange;
    }

    // Property selectors
    public PropertySelector<SgediRccidotation, Integer> getDottypSelector() {
        return dottypSelector;
    }

    // Relation selectors
    public PropertySelector<SgediRccidotation, Sgedircci> getIdrcciSelector() {
        return idrcciSelector;
    }
}
