/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediTitrerffi;
import ma.sgma.edi2.printer.SgediTitrerffiPrinter;
import ma.sgma.edi2.repository.SgediTitrerffiRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgediTitrerffiPermission;

/**
 * Stateless controller for {@link SgediTitrerffi} conversation start.
 */
@Named
@Singleton
public class SgediTitrerffiController extends GenericController<SgediTitrerffi, Integer> {
    public static final String SGEDITITRERFFI_EDIT_URI = "/domain/sgediTitrerffiEdit.faces";
    public static final String SGEDITITRERFFI_SELECT_URI = "/domain/sgediTitrerffiSelect.faces";

    @Inject
    public SgediTitrerffiController(SgediTitrerffiRepository sgediTitrerffiRepository, SgediTitrerffiPermission sgediTitrerffiPermission,
            SgediTitrerffiPrinter sgediTitrerffiPrinter) {
        super(sgediTitrerffiRepository, sgediTitrerffiPermission, sgediTitrerffiPrinter, SGEDITITRERFFI_SELECT_URI, SGEDITITRERFFI_EDIT_URI);
    }
}