/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.printer.SgedixmlPrinter;
import ma.sgma.edi2.repository.SgedixmlRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgedixmlPermission;

/**
 * Stateless controller for {@link Sgedixml} conversation start.
 */
@Named
@Singleton
public class SgedixmlController extends GenericController<Sgedixml, Integer> {
    public static final String SGEDIXML_EDIT_URI = "/domain/sgedixmlEdit.faces";
    public static final String SGEDIXML_SELECT_URI = "/domain/sgedixmlSelect.faces";

    @Inject
    public SgedixmlController(SgedixmlRepository sgedixmlRepository, SgedixmlPermission sgedixmlPermission, SgedixmlPrinter sgedixmlPrinter) {
        super(sgedixmlRepository, sgedixmlPermission, sgedixmlPrinter, SGEDIXML_SELECT_URI, SGEDIXML_EDIT_URI);
    }
}