/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgedirffiErrors;
import ma.sgma.edi2.printer.SgedirffiErrorsPrinter;
import ma.sgma.edi2.repository.SgedirffiErrorsRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgedirffiErrorsPermission;

/**
 * Stateless controller for {@link SgedirffiErrors} conversation start.
 */
@Named
@Singleton
public class SgedirffiErrorsController extends GenericController<SgedirffiErrors, Integer> {
    public static final String SGEDIRFFIERRORS_EDIT_URI = "/domain/sgedirffiErrorsEdit.faces";
    public static final String SGEDIRFFIERRORS_SELECT_URI = "/domain/sgedirffiErrorsSelect.faces";

    @Inject
    public SgedirffiErrorsController(SgedirffiErrorsRepository sgedirffiErrorsRepository, SgedirffiErrorsPermission sgedirffiErrorsPermission,
            SgedirffiErrorsPrinter sgedirffiErrorsPrinter) {
        super(sgedirffiErrorsRepository, sgedirffiErrorsPermission, sgedirffiErrorsPrinter, SGEDIRFFIERRORS_SELECT_URI, SGEDIRFFIERRORS_EDIT_URI);
    }
}