/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediDictodc;
import ma.sgma.edi2.printer.SgediDictodcPrinter;
import ma.sgma.edi2.repository.SgediDictodcRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgediDictodcPermission;

/**
 * Stateless controller for {@link SgediDictodc} conversation start.
 */
@Named
@Singleton
public class SgediDictodcController extends GenericController<SgediDictodc, Integer> {
    public static final String SGEDIDICTODC_EDIT_URI = "/domain/sgediDictodcEdit.faces";
    public static final String SGEDIDICTODC_SELECT_URI = "/domain/sgediDictodcSelect.faces";

    @Inject
    public SgediDictodcController(SgediDictodcRepository sgediDictodcRepository, SgediDictodcPermission sgediDictodcPermission,
            SgediDictodcPrinter sgediDictodcPrinter) {
        super(sgediDictodcRepository, sgediDictodcPermission, sgediDictodcPrinter, SGEDIDICTODC_SELECT_URI, SGEDIDICTODC_EDIT_URI);
    }
}