/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Sgedircci} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SgedircciExcelExporter extends GenericExcelExporter<Sgedircci> {
    @Inject
    protected SgedircciSearchForm sf;

    public SgedircciExcelExporter() {
        super("sgedircci_codeLigne", "sgedircci_codeBanque", "sgedircci_codeLocalite", "sgedircci_numeroGuichet", "sgedircci_anneeRcc", "sgedircci_moisRcc");
    }

    @Override
    protected void fillResultItem(int row, Sgedircci item) {
        int col = 0;
        setValue(row, col++, item.getCodeLigne());
        setValue(row, col++, item.getCodeBanque());
        setValue(row, col++, item.getCodeLocalite());
        setValue(row, col++, item.getNumeroGuichet());
        setValue(row, col++, item.getAnneeRcc());
        setValue(row, col++, item.getMoisRcc());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "sgedircci_codeLigne", sf.getCodeLigneSelector());
        setSelector(row++, 0, "sgedircci_codeBanque", sf.getCodeBanqueSelector());
        setSelector(row++, 0, "sgedircci_codeLocalite", sf.getCodeLocaliteSelector());
        setSelector(row++, 0, "sgedircci_numeroGuichet", sf.getNumeroGuichetSelector());
        setSelector(row++, 0, "sgedircci_anneeRcc", sf.getAnneeRccSelector());
        setSelector(row++, 0, "sgedircci_moisRcc", sf.getMoisRccSelector());
        setRangeNumber(row++, 0, "sgedircci_ncompteCarte", sf.getNcompteCarteRange());
        setRangeNumber(row++, 0, "sgedircci_rcompteCarte", sf.getRcompteCarteRange());
        setRangeNumber(row++, 0, "sgedircci_douvertureEmission", sf.getDouvertureEmissionRange());
        setSelector(row++, 0, "sgedircci_dcompteCarte", sf.getDcompteCarteSelector());
        setSelector(row++, 0, "sgedircci_nomRsociale", sf.getNomRsocialeSelector());
        setSelectedEntities(row++, 0, "sgedircci_qualiteSclient", sf.getQualiteSclientSelector().getSelected());
        setSelectedEntities(row++, 0, "sgedircci_typeIdentification", sf.getTypeIdentificationSelector().getSelected());
        setSelector(row++, 0, "sgedircci_numIdentification", sf.getNumIdentificationSelector());
        setSelector(row++, 0, "sgedircci_centreRc", sf.getCentreRcSelector());
        setSelector(row++, 0, "sgedircci_rc", sf.getRcSelector());
        setSelector(row++, 0, "sgedircci_pays", sf.getPaysSelector());
        setSelector(row++, 0, "sgedircci_ville", sf.getVilleSelector());
        setSelector(row++, 0, "sgedircci_adresse", sf.getAdresseSelector());
        setRangeNumber(row++, 0, "sgedircci_sdebut", sf.getSdebutRange());
        setRangeNumber(row++, 0, "sgedircci_totalMcredit", sf.getTotalMcreditRange());
        setRangeNumber(row++, 0, "sgedircci_totalMdebit", sf.getTotalMdebitRange());
        setRangeNumber(row++, 0, "sgedircci_soldeFmois", sf.getSoldeFmoisRange());
        setSelector(row++, 0, "sgedircci_champSupp2", sf.getChampSupp2Selector());
        setSelector(row++, 0, "sgedircci_champSupp3", sf.getChampSupp3Selector());
        setSelector(row++, 0, "sgedircci_champSupp4", sf.getChampSupp4Selector());
        setSelector(row++, 0, "sgedircci_champSupp5", sf.getChampSupp5Selector());
        setSelectedEntities(row++, 0, "sgedircci_statutInt", sf.getStatutIntSelector().getSelected());
        setSelectedEntities(row++, 0, "sgedircci_statutEch", sf.getStatutEchSelector().getSelected());
        setSelectedEntities(row++, 0, "sgedircci_codeErr", sf.getCodeErrSelector().getSelected());
        setSelector(row++, 0, "sgedircci_motif", sf.getMotifSelector());
        setSelectedEntities(row++, 0, "sgedircci_codeRole", sf.getCodeRoleSelector().getSelected());
        setSelectedEntities(row++, 0, "sgedircci_idXml", sf.getIdXmlSelector().getSelected());
        setSelector(row++, 0, "sgedircci_lib1", sf.getLib1Selector());
        setSelector(row++, 0, "sgedircci_lib2", sf.getLib2Selector());
        setSelector(row++, 0, "sgedircci_lib3", sf.getLib3Selector());
    }
}