/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;
import static com.jaxio.jpa.querybyexample.Range.newRange;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.Range;
import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgediDictodc;
import ma.sgma.edi2.domain.SgediParams;
import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.domain.Sgedircci_;
import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.domain.Userrole;
import ma.sgma.edi2.web.domain.support.GenericSearchForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Sgedircci}.
 * It exposes a {@link Sgedircci} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SgedircciSearchForm extends GenericSearchForm<Sgedircci, Integer, SgedircciSearchForm> {
    private static final long serialVersionUID = 1L;
    protected Sgedircci sgedircci = new Sgedircci();
    protected Range<Sgedircci, Integer> ncompteCarteRange = newRange(Sgedircci_.ncompteCarte);
    protected Range<Sgedircci, Integer> rcompteCarteRange = newRange(Sgedircci_.rcompteCarte);
    protected Range<Sgedircci, Integer> douvertureEmissionRange = newRange(Sgedircci_.douvertureEmission);
    protected Range<Sgedircci, Long> sdebutRange = newRange(Sgedircci_.sdebut);
    protected Range<Sgedircci, Long> totalMcreditRange = newRange(Sgedircci_.totalMcredit);
    protected Range<Sgedircci, Long> totalMdebitRange = newRange(Sgedircci_.totalMdebit);
    protected Range<Sgedircci, Long> soldeFmoisRange = newRange(Sgedircci_.soldeFmois);
    protected PropertySelector<Sgedircci, String> codeLigneSelector = newPropertySelector(Sgedircci_.codeLigne);
    protected PropertySelector<Sgedircci, String> codeBanqueSelector = newPropertySelector(Sgedircci_.codeBanque);
    protected PropertySelector<Sgedircci, String> codeLocaliteSelector = newPropertySelector(Sgedircci_.codeLocalite);
    protected PropertySelector<Sgedircci, String> numeroGuichetSelector = newPropertySelector(Sgedircci_.numeroGuichet);
    protected PropertySelector<Sgedircci, String> anneeRccSelector = newPropertySelector(Sgedircci_.anneeRcc);
    protected PropertySelector<Sgedircci, String> moisRccSelector = newPropertySelector(Sgedircci_.moisRcc);
    protected PropertySelector<Sgedircci, Integer> ncompteCarteSelector = newPropertySelector(Sgedircci_.ncompteCarte);
    protected PropertySelector<Sgedircci, Integer> rcompteCarteSelector = newPropertySelector(Sgedircci_.rcompteCarte);
    protected PropertySelector<Sgedircci, Integer> douvertureEmissionSelector = newPropertySelector(Sgedircci_.douvertureEmission);
    protected PropertySelector<Sgedircci, String> dcompteCarteSelector = newPropertySelector(Sgedircci_.dcompteCarte);
    protected PropertySelector<Sgedircci, String> nomRsocialeSelector = newPropertySelector(Sgedircci_.nomRsociale);
    protected PropertySelector<Sgedircci, String> numIdentificationSelector = newPropertySelector(Sgedircci_.numIdentification);
    protected PropertySelector<Sgedircci, String> centreRcSelector = newPropertySelector(Sgedircci_.centreRc);
    protected PropertySelector<Sgedircci, String> rcSelector = newPropertySelector(Sgedircci_.rc);
    protected PropertySelector<Sgedircci, String> paysSelector = newPropertySelector(Sgedircci_.pays);
    protected PropertySelector<Sgedircci, String> villeSelector = newPropertySelector(Sgedircci_.ville);
    protected PropertySelector<Sgedircci, String> adresseSelector = newPropertySelector(Sgedircci_.adresse);
    protected PropertySelector<Sgedircci, Long> sdebutSelector = newPropertySelector(Sgedircci_.sdebut);
    protected PropertySelector<Sgedircci, Long> totalMcreditSelector = newPropertySelector(Sgedircci_.totalMcredit);
    protected PropertySelector<Sgedircci, Long> totalMdebitSelector = newPropertySelector(Sgedircci_.totalMdebit);
    protected PropertySelector<Sgedircci, Long> soldeFmoisSelector = newPropertySelector(Sgedircci_.soldeFmois);
    protected PropertySelector<Sgedircci, String> champSupp2Selector = newPropertySelector(Sgedircci_.champSupp2);
    protected PropertySelector<Sgedircci, String> champSupp3Selector = newPropertySelector(Sgedircci_.champSupp3);
    protected PropertySelector<Sgedircci, String> champSupp4Selector = newPropertySelector(Sgedircci_.champSupp4);
    protected PropertySelector<Sgedircci, String> champSupp5Selector = newPropertySelector(Sgedircci_.champSupp5);
    protected PropertySelector<Sgedircci, String> motifSelector = newPropertySelector(Sgedircci_.motif);
    protected PropertySelector<Sgedircci, String> lib1Selector = newPropertySelector(Sgedircci_.lib1);
    protected PropertySelector<Sgedircci, String> lib2Selector = newPropertySelector(Sgedircci_.lib2);
    protected PropertySelector<Sgedircci, String> lib3Selector = newPropertySelector(Sgedircci_.lib3);
    protected PropertySelector<Sgedircci, SgediDictodc> qualiteSclientSelector = newPropertySelector(Sgedircci_.qualiteSclient);
    protected PropertySelector<Sgedircci, Userrole> codeRoleSelector = newPropertySelector(Sgedircci_.codeRole);
    protected PropertySelector<Sgedircci, Sgedixml> idXmlSelector = newPropertySelector(Sgedircci_.idXml);
    protected PropertySelector<Sgedircci, SgediParams> statutIntSelector = newPropertySelector(Sgedircci_.statutInt);
    protected PropertySelector<Sgedircci, SgediDictodc> typeIdentificationSelector = newPropertySelector(Sgedircci_.typeIdentification);
    protected PropertySelector<Sgedircci, SgediParams> statutEchSelector = newPropertySelector(Sgedircci_.statutEch);
    protected PropertySelector<Sgedircci, SgediParams> codeErrSelector = newPropertySelector(Sgedircci_.codeErr);

    public Sgedircci getSgedircci() {
        return sgedircci;
    }

    @Override
    protected Sgedircci getEntity() {
        return getSgedircci();
    }

    @Override
    public SgedircciSearchForm newInstance() {
        return new SgedircciSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(ncompteCarteRange, rcompteCarteRange, douvertureEmissionRange, sdebutRange, totalMcreditRange, totalMdebitRange, soldeFmoisRange);
        sp.property(codeLigneSelector, codeBanqueSelector, codeLocaliteSelector, numeroGuichetSelector, anneeRccSelector, moisRccSelector, ncompteCarteSelector,
                rcompteCarteSelector, douvertureEmissionSelector, dcompteCarteSelector, nomRsocialeSelector, numIdentificationSelector, centreRcSelector,
                rcSelector, paysSelector, villeSelector, adresseSelector, sdebutSelector, totalMcreditSelector, totalMdebitSelector, soldeFmoisSelector,
                champSupp2Selector, champSupp3Selector, champSupp4Selector, champSupp5Selector, motifSelector, lib1Selector, lib2Selector, lib3Selector);
        sp.property(qualiteSclientSelector, codeRoleSelector, idXmlSelector, statutIntSelector, typeIdentificationSelector, statutEchSelector, codeErrSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SgedircciSearchForm other) {
        this.sgedircci = other.getSgedircci();
        this.ncompteCarteRange = other.getNcompteCarteRange();
        this.rcompteCarteRange = other.getRcompteCarteRange();
        this.douvertureEmissionRange = other.getDouvertureEmissionRange();
        this.sdebutRange = other.getSdebutRange();
        this.totalMcreditRange = other.getTotalMcreditRange();
        this.totalMdebitRange = other.getTotalMdebitRange();
        this.soldeFmoisRange = other.getSoldeFmoisRange();
        this.codeLigneSelector = other.getCodeLigneSelector();
        this.codeBanqueSelector = other.getCodeBanqueSelector();
        this.codeLocaliteSelector = other.getCodeLocaliteSelector();
        this.numeroGuichetSelector = other.getNumeroGuichetSelector();
        this.anneeRccSelector = other.getAnneeRccSelector();
        this.moisRccSelector = other.getMoisRccSelector();
        this.ncompteCarteSelector = other.getNcompteCarteSelector();
        this.rcompteCarteSelector = other.getRcompteCarteSelector();
        this.douvertureEmissionSelector = other.getDouvertureEmissionSelector();
        this.dcompteCarteSelector = other.getDcompteCarteSelector();
        this.nomRsocialeSelector = other.getNomRsocialeSelector();
        this.numIdentificationSelector = other.getNumIdentificationSelector();
        this.centreRcSelector = other.getCentreRcSelector();
        this.rcSelector = other.getRcSelector();
        this.paysSelector = other.getPaysSelector();
        this.villeSelector = other.getVilleSelector();
        this.adresseSelector = other.getAdresseSelector();
        this.sdebutSelector = other.getSdebutSelector();
        this.totalMcreditSelector = other.getTotalMcreditSelector();
        this.totalMdebitSelector = other.getTotalMdebitSelector();
        this.soldeFmoisSelector = other.getSoldeFmoisSelector();
        this.champSupp2Selector = other.getChampSupp2Selector();
        this.champSupp3Selector = other.getChampSupp3Selector();
        this.champSupp4Selector = other.getChampSupp4Selector();
        this.champSupp5Selector = other.getChampSupp5Selector();
        this.motifSelector = other.getMotifSelector();
        this.lib1Selector = other.getLib1Selector();
        this.lib2Selector = other.getLib2Selector();
        this.lib3Selector = other.getLib3Selector();
        this.qualiteSclientSelector = other.getQualiteSclientSelector();
        this.codeRoleSelector = other.getCodeRoleSelector();
        this.idXmlSelector = other.getIdXmlSelector();
        this.statutIntSelector = other.getStatutIntSelector();
        this.typeIdentificationSelector = other.getTypeIdentificationSelector();
        this.statutEchSelector = other.getStatutEchSelector();
        this.codeErrSelector = other.getCodeErrSelector();
    }

    // Ranges
    public Range<Sgedircci, Integer> getNcompteCarteRange() {
        return ncompteCarteRange;
    }

    public Range<Sgedircci, Integer> getRcompteCarteRange() {
        return rcompteCarteRange;
    }

    public Range<Sgedircci, Integer> getDouvertureEmissionRange() {
        return douvertureEmissionRange;
    }

    public Range<Sgedircci, Long> getSdebutRange() {
        return sdebutRange;
    }

    public Range<Sgedircci, Long> getTotalMcreditRange() {
        return totalMcreditRange;
    }

    public Range<Sgedircci, Long> getTotalMdebitRange() {
        return totalMdebitRange;
    }

    public Range<Sgedircci, Long> getSoldeFmoisRange() {
        return soldeFmoisRange;
    }

    // Property selectors
    public PropertySelector<Sgedircci, String> getCodeLigneSelector() {
        return codeLigneSelector;
    }

    public PropertySelector<Sgedircci, String> getCodeBanqueSelector() {
        return codeBanqueSelector;
    }

    public PropertySelector<Sgedircci, String> getCodeLocaliteSelector() {
        return codeLocaliteSelector;
    }

    public PropertySelector<Sgedircci, String> getNumeroGuichetSelector() {
        return numeroGuichetSelector;
    }

    public PropertySelector<Sgedircci, String> getAnneeRccSelector() {
        return anneeRccSelector;
    }

    public PropertySelector<Sgedircci, String> getMoisRccSelector() {
        return moisRccSelector;
    }

    public PropertySelector<Sgedircci, Integer> getNcompteCarteSelector() {
        return ncompteCarteSelector;
    }

    public PropertySelector<Sgedircci, Integer> getRcompteCarteSelector() {
        return rcompteCarteSelector;
    }

    public PropertySelector<Sgedircci, Integer> getDouvertureEmissionSelector() {
        return douvertureEmissionSelector;
    }

    public PropertySelector<Sgedircci, String> getDcompteCarteSelector() {
        return dcompteCarteSelector;
    }

    public PropertySelector<Sgedircci, String> getNomRsocialeSelector() {
        return nomRsocialeSelector;
    }

    public PropertySelector<Sgedircci, String> getNumIdentificationSelector() {
        return numIdentificationSelector;
    }

    public PropertySelector<Sgedircci, String> getCentreRcSelector() {
        return centreRcSelector;
    }

    public PropertySelector<Sgedircci, String> getRcSelector() {
        return rcSelector;
    }

    public PropertySelector<Sgedircci, String> getPaysSelector() {
        return paysSelector;
    }

    public PropertySelector<Sgedircci, String> getVilleSelector() {
        return villeSelector;
    }

    public PropertySelector<Sgedircci, String> getAdresseSelector() {
        return adresseSelector;
    }

    public PropertySelector<Sgedircci, Long> getSdebutSelector() {
        return sdebutSelector;
    }

    public PropertySelector<Sgedircci, Long> getTotalMcreditSelector() {
        return totalMcreditSelector;
    }

    public PropertySelector<Sgedircci, Long> getTotalMdebitSelector() {
        return totalMdebitSelector;
    }

    public PropertySelector<Sgedircci, Long> getSoldeFmoisSelector() {
        return soldeFmoisSelector;
    }

    public PropertySelector<Sgedircci, String> getChampSupp2Selector() {
        return champSupp2Selector;
    }

    public PropertySelector<Sgedircci, String> getChampSupp3Selector() {
        return champSupp3Selector;
    }

    public PropertySelector<Sgedircci, String> getChampSupp4Selector() {
        return champSupp4Selector;
    }

    public PropertySelector<Sgedircci, String> getChampSupp5Selector() {
        return champSupp5Selector;
    }

    public PropertySelector<Sgedircci, String> getMotifSelector() {
        return motifSelector;
    }

    public PropertySelector<Sgedircci, String> getLib1Selector() {
        return lib1Selector;
    }

    public PropertySelector<Sgedircci, String> getLib2Selector() {
        return lib2Selector;
    }

    public PropertySelector<Sgedircci, String> getLib3Selector() {
        return lib3Selector;
    }

    // Relation selectors
    public PropertySelector<Sgedircci, SgediDictodc> getQualiteSclientSelector() {
        return qualiteSclientSelector;
    }

    public PropertySelector<Sgedircci, Userrole> getCodeRoleSelector() {
        return codeRoleSelector;
    }

    public PropertySelector<Sgedircci, Sgedixml> getIdXmlSelector() {
        return idXmlSelector;
    }

    public PropertySelector<Sgedircci, SgediParams> getStatutIntSelector() {
        return statutIntSelector;
    }

    public PropertySelector<Sgedircci, SgediDictodc> getTypeIdentificationSelector() {
        return typeIdentificationSelector;
    }

    public PropertySelector<Sgedircci, SgediParams> getStatutEchSelector() {
        return statutEchSelector;
    }

    public PropertySelector<Sgedircci, SgediParams> getCodeErrSelector() {
        return codeErrSelector;
    }
}
