/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;
import static com.jaxio.jpa.querybyexample.Range.newRange;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.Range;
import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgediDictodc;
import ma.sgma.edi2.domain.SgediDictodc_;
import ma.sgma.edi2.web.domain.support.GenericSearchForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link SgediDictodc}.
 * It exposes a {@link SgediDictodc} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SgediDictodcSearchForm extends GenericSearchForm<SgediDictodc, Integer, SgediDictodcSearchForm> {
    private static final long serialVersionUID = 1L;
    protected SgediDictodc sgediDictodc = new SgediDictodc();
    protected Range<SgediDictodc, Integer> codeRange = newRange(SgediDictodc_.code);
    protected PropertySelector<SgediDictodc, Integer> codeSelector = newPropertySelector(SgediDictodc_.code);
    protected PropertySelector<SgediDictodc, String> libelleSelector = newPropertySelector(SgediDictodc_.libelle);
    protected PropertySelector<SgediDictodc, String> lib1Selector = newPropertySelector(SgediDictodc_.lib1);
    protected PropertySelector<SgediDictodc, String> lib2Selector = newPropertySelector(SgediDictodc_.lib2);
    protected PropertySelector<SgediDictodc, String> lib3Selector = newPropertySelector(SgediDictodc_.lib3);

    public SgediDictodc getSgediDictodc() {
        return sgediDictodc;
    }

    @Override
    protected SgediDictodc getEntity() {
        return getSgediDictodc();
    }

    @Override
    public SgediDictodcSearchForm newInstance() {
        return new SgediDictodcSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(codeRange);
        sp.property(codeSelector, libelleSelector, lib1Selector, lib2Selector, lib3Selector);
        return sp;
    }

    @Override
    public void resetWithOther(SgediDictodcSearchForm other) {
        this.sgediDictodc = other.getSgediDictodc();
        this.codeRange = other.getCodeRange();
        this.codeSelector = other.getCodeSelector();
        this.libelleSelector = other.getLibelleSelector();
        this.lib1Selector = other.getLib1Selector();
        this.lib2Selector = other.getLib2Selector();
        this.lib3Selector = other.getLib3Selector();
    }

    // Ranges
    public Range<SgediDictodc, Integer> getCodeRange() {
        return codeRange;
    }

    // Property selectors
    public PropertySelector<SgediDictodc, Integer> getCodeSelector() {
        return codeSelector;
    }

    public PropertySelector<SgediDictodc, String> getLibelleSelector() {
        return libelleSelector;
    }

    public PropertySelector<SgediDictodc, String> getLib1Selector() {
        return lib1Selector;
    }

    public PropertySelector<SgediDictodc, String> getLib2Selector() {
        return lib2Selector;
    }

    public PropertySelector<SgediDictodc, String> getLib3Selector() {
        return lib3Selector;
    }
}
