/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;
import static com.jaxio.jpa.querybyexample.Range.newRange;

import java.util.Date;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.Range;
import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.domain.Sgedixml_;
import ma.sgma.edi2.web.domain.support.GenericSearchForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Sgedixml}.
 * It exposes a {@link Sgedixml} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SgedixmlSearchForm extends GenericSearchForm<Sgedixml, Integer, SgedixmlSearchForm> {
    private static final long serialVersionUID = 1L;
    protected Sgedixml sgedixml = new Sgedixml();
    protected Range<Sgedixml, Integer> sensRange = newRange(Sgedixml_.sens);
    protected Range<Sgedixml, Integer> anneRange = newRange(Sgedixml_.anne);
    protected Range<Sgedixml, Integer> moisRange = newRange(Sgedixml_.mois);
    protected Range<Sgedixml, Integer> decadeRange = newRange(Sgedixml_.decade);
    protected Range<Sgedixml, Date> dateGenRange = newRange(Sgedixml_.dateGen);
    protected PropertySelector<Sgedixml, String> xmlSelector = newPropertySelector(Sgedixml_.xml);
    protected PropertySelector<Sgedixml, Integer> sensSelector = newPropertySelector(Sgedixml_.sens);
    protected PropertySelector<Sgedixml, String> typSelector = newPropertySelector(Sgedixml_.typ);
    protected PropertySelector<Sgedixml, Integer> anneSelector = newPropertySelector(Sgedixml_.anne);
    protected PropertySelector<Sgedixml, Integer> moisSelector = newPropertySelector(Sgedixml_.mois);
    protected PropertySelector<Sgedixml, Integer> decadeSelector = newPropertySelector(Sgedixml_.decade);

    public Sgedixml getSgedixml() {
        return sgedixml;
    }

    @Override
    protected Sgedixml getEntity() {
        return getSgedixml();
    }

    @Override
    public SgedixmlSearchForm newInstance() {
        return new SgedixmlSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(sensRange, anneRange, moisRange, decadeRange, dateGenRange);
        sp.property(xmlSelector, sensSelector, typSelector, anneSelector, moisSelector, decadeSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SgedixmlSearchForm other) {
        this.sgedixml = other.getSgedixml();
        this.sensRange = other.getSensRange();
        this.anneRange = other.getAnneRange();
        this.moisRange = other.getMoisRange();
        this.decadeRange = other.getDecadeRange();
        this.dateGenRange = other.getDateGenRange();
        this.xmlSelector = other.getXmlSelector();
        this.sensSelector = other.getSensSelector();
        this.typSelector = other.getTypSelector();
        this.anneSelector = other.getAnneSelector();
        this.moisSelector = other.getMoisSelector();
        this.decadeSelector = other.getDecadeSelector();
    }

    // Ranges
    public Range<Sgedixml, Integer> getSensRange() {
        return sensRange;
    }

    public Range<Sgedixml, Integer> getAnneRange() {
        return anneRange;
    }

    public Range<Sgedixml, Integer> getMoisRange() {
        return moisRange;
    }

    public Range<Sgedixml, Integer> getDecadeRange() {
        return decadeRange;
    }

    public Range<Sgedixml, Date> getDateGenRange() {
        return dateGenRange;
    }

    // Property selectors
    public PropertySelector<Sgedixml, String> getXmlSelector() {
        return xmlSelector;
    }

    public PropertySelector<Sgedixml, Integer> getSensSelector() {
        return sensSelector;
    }

    public PropertySelector<Sgedixml, String> getTypSelector() {
        return typSelector;
    }

    public PropertySelector<Sgedixml, Integer> getAnneSelector() {
        return anneSelector;
    }

    public PropertySelector<Sgedixml, Integer> getMoisSelector() {
        return moisSelector;
    }

    public PropertySelector<Sgedixml, Integer> getDecadeSelector() {
        return decadeSelector;
    }
}
