/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.SgediRccidotation;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link SgediRccidotation} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SgediRccidotationExcelExporter extends GenericExcelExporter<SgediRccidotation> {
    @Inject
    protected SgediRccidotationSearchForm sf;

    public SgediRccidotationExcelExporter() {
        super("sgediRccidotation_idrcci", "sgediRccidotation_dottyp");
    }

    @Override
    protected void fillResultItem(int row, SgediRccidotation item) {
        int col = 0;
        setEntity(row, col++, item.getIdrcci());
        setValue(row, col++, item.getDottyp());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "sgediRccidotation_idrcci", sf.getIdrcciSelector().getSelected());
        setRangeNumber(row++, 0, "sgediRccidotation_dottyp", sf.getDottypRange());
    }
}