/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.repository.SgedixmlRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Sgedixml}.
 */
@Named
@ConversationContextScoped
public class SgedixmlEditForm extends GenericEditForm<Sgedixml, Integer> {
    @Inject
    protected SgedixmlController sgedixmlController;

    @Inject
    public SgedixmlEditForm(SgedixmlRepository sgedixmlRepository) {
        super(sgedixmlRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Sgedixml getSgedixml() {
        return getEntity();
    }

    public String print() {
        return sgedixmlController.print(getSgedixml());
    }
}
