/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.EntityGraphLoader;

import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.repository.SgedirffiRepository;

/**
 * Preloads the {@link Sgedirffi} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class SgedirffiGraphLoader extends EntityGraphLoader<Sgedirffi, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected SgedirffiGraphLoader() {
        super();
    }

    @Inject
    public SgedirffiGraphLoader(SgedirffiRepository sgedirffiRepository) {
        super(sgedirffiRepository);
    }

    @Override
    public void loadGraph(Sgedirffi sgedirffi) {
        loadSingular(sgedirffi.getIdXml());
        loadSingular(sgedirffi.getTypeIdentification());
        loadSingular(sgedirffi.getStatutInt());
        loadSingular(sgedirffi.getQualite());
        loadSingular(sgedirffi.getCodeRole());
        loadSingular(sgedirffi.getCategorieFormule());
        loadSingular(sgedirffi.getSensOperation());
        loadSingular(sgedirffi.getStatutEch());
        loadCollection(sgedirffi.getSgedirffiErrorss());
        loadCollection(sgedirffi.getSgediTitrerffis());
    }
}