/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.domain.SgedirffiErrors;
import ma.sgma.edi2.domain.SgedirffiErrors_;
import ma.sgma.edi2.repository.SgedirffiErrorsRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.domain.support.GenericToOneAssociation;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SgedirffiErrors}.
 */
@Named
@ConversationContextScoped
public class SgedirffiErrorsEditForm extends GenericEditForm<SgedirffiErrors, Integer> {
    @Inject
    protected SgedirffiErrorsController sgedirffiErrorsController;
    @Inject
    protected SgedirffiController sgedirffiController;
    protected GenericToOneAssociation<Sgedirffi, Integer> coderffi;

    @Inject
    public SgedirffiErrorsEditForm(SgedirffiErrorsRepository sgedirffiErrorsRepository, SgedirffiErrorsGraphLoader sgedirffiErrorsGraphLoader) {
        super(sgedirffiErrorsRepository, sgedirffiErrorsGraphLoader);
        this.setModule("ERROS");

    }

    /**
     * The entity to edit/view.
     */
    public SgedirffiErrors getSgedirffiErrors() {
        return getEntity();
    }

    public String print() {
        return sgedirffiErrorsController.print(getSgedirffiErrors());
    }

    @PostConstruct
    void setupCoderffiActions() {
        coderffi = new GenericToOneAssociation<Sgedirffi, Integer>(sgedirffiController, SgedirffiErrors_.coderffi) {
            @Override
            protected Sgedirffi get() {
                return getSgedirffiErrors().getCoderffi();
            }

            @Override
            protected void set(Sgedirffi sgedirffi) {
                getSgedirffiErrors().setCoderffi(sgedirffi);
            }
        };
    }

    public GenericToOneAssociation<Sgedirffi, Integer> getCoderffi() {
        return coderffi;
    }
}
