/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Sgedixml;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Sgedixml} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SgedixmlExcelExporter extends GenericExcelExporter<Sgedixml> {
    @Inject
    protected SgedixmlSearchForm sf;

    public SgedixmlExcelExporter() {
        super("sgedixml_xml", "sgedixml_sens", "sgedixml_typ", "sgedixml_anne", "sgedixml_mois", "sgedixml_decade");
    }

    @Override
    protected void fillResultItem(int row, Sgedixml item) {
        int col = 0;
        setValue(row, col++, item.getXml());
        setValue(row, col++, item.getSens());
        setValue(row, col++, item.getTyp());
        setValue(row, col++, item.getAnne());
        setValue(row, col++, item.getMois());
        setValue(row, col++, item.getDecade());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "sgedixml_xml", sf.getXmlSelector());
        setRangeNumber(row++, 0, "sgedixml_sens", sf.getSensRange());
        setSelector(row++, 0, "sgedixml_typ", sf.getTypSelector());
        setRangeNumber(row++, 0, "sgedixml_anne", sf.getAnneRange());
        setRangeNumber(row++, 0, "sgedixml_mois", sf.getMoisRange());
        setRangeNumber(row++, 0, "sgedixml_decade", sf.getDecadeRange());
        setRangeDateTime(row++, 0, "sgedixml_dateGen", sf.getDateGenRange());
    }
}