/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.SgediTitrerffi;
import ma.sgma.edi2.domain.SgediTitrerffi_;
import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.repository.SgediTitrerffiRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.domain.support.GenericToOneAssociation;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SgediTitrerffi}.
 */
@Named
@ConversationContextScoped
public class SgediTitrerffiEditForm extends GenericEditForm<SgediTitrerffi, Integer> {
    @Inject
    protected SgediTitrerffiController sgediTitrerffiController;
    @Inject
    protected SgedirffiController sgedirffiController;
    protected GenericToOneAssociation<Sgedirffi, Integer> idrffi;

    @Inject
    public SgediTitrerffiEditForm(SgediTitrerffiRepository sgediTitrerffiRepository, SgediTitrerffiGraphLoader sgediTitrerffiGraphLoader) {
        super(sgediTitrerffiRepository, sgediTitrerffiGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SgediTitrerffi getSgediTitrerffi() {
        return getEntity();
    }

    public String print() {
        return sgediTitrerffiController.print(getSgediTitrerffi());
    }

    @PostConstruct
    void setupIdrffiActions() {
        idrffi = new GenericToOneAssociation<Sgedirffi, Integer>(sgedirffiController, SgediTitrerffi_.idrffi) {
            @Override
            protected Sgedirffi get() {
                return getSgediTitrerffi().getIdrffi();
            }

            @Override
            protected void set(Sgedirffi sgedirffi) {
                getSgediTitrerffi().setIdrffi(sgedirffi);
            }
        };
    }

    public GenericToOneAssociation<Sgedirffi, Integer> getIdrffi() {
        return idrffi;
    }
}
