/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.EntityGraphLoader;

import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.repository.SgedircciRepository;

/**
 * Preloads the {@link Sgedircci} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class SgedircciGraphLoader extends EntityGraphLoader<Sgedircci, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected SgedircciGraphLoader() {
        super();
    }

    @Inject
    public SgedircciGraphLoader(SgedircciRepository sgedircciRepository) {
        super(sgedircciRepository);
    }

    @Override
    public void loadGraph(Sgedircci sgedircci) {
        loadSingular(sgedircci.getQualiteSclient());
        loadSingular(sgedircci.getCodeRole());
        loadSingular(sgedircci.getIdXml());
        loadSingular(sgedircci.getStatutInt());
        loadSingular(sgedircci.getTypeIdentification());
        loadSingular(sgedircci.getStatutEch());
        loadSingular(sgedircci.getCodeErr());
        loadCollection(sgedircci.getSgediRccidotations());
        loadCollection(sgedircci.getSgediEdircciMos());
    }
}