/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.SgediEdircciMo;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link SgediEdircciMo} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SgediEdircciMoExcelExporter extends GenericExcelExporter<SgediEdircciMo> {
    @Inject
    protected SgediEdircciMoSearchForm sf;

    public SgediEdircciMoExcelExporter() {
        super("sgediEdircciMo_idrcci", "sgediEdircciMo_mouvrage");
    }

    @Override
    protected void fillResultItem(int row, SgediEdircciMo item) {
        int col = 0;
        setEntity(row, col++, item.getIdrcci());
        setValue(row, col++, item.getMouvrage());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "sgediEdircciMo_idrcci", sf.getIdrcciSelector().getSelected());
        setSelector(row++, 0, "sgediEdircciMo_mouvrage", sf.getMouvrageSelector());
    }
}