/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediParams;
import ma.sgma.edi2.printer.SgediParamsPrinter;
import ma.sgma.edi2.repository.SgediParamsRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgediParamsPermission;

/**
 * Stateless controller for {@link SgediParams} conversation start.
 */
@Named
@Singleton
public class SgediParamsController extends GenericController<SgediParams, Integer> {
    public static final String SGEDIPARAMS_EDIT_URI = "/domain/sgediParamsEdit.faces";
    public static final String SGEDIPARAMS_SELECT_URI = "/domain/sgediParamsSelect.faces";

    @Inject
    public SgediParamsController(SgediParamsRepository sgediParamsRepository, SgediParamsPermission sgediParamsPermission,
            SgediParamsPrinter sgediParamsPrinter) {
        super(sgediParamsRepository, sgediParamsPermission, sgediParamsPrinter, SGEDIPARAMS_SELECT_URI, SGEDIPARAMS_EDIT_URI);
    }
}