/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import ma.sgma.edi2.domain.SgediRccidotation;
import ma.sgma.edi2.domain.SgediRccidotation_;
import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.repository.SgediRccidotationRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.domain.support.GenericToOneAssociation;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SgediRccidotation}.
 */
@Named
@ConversationContextScoped
public class SgediRccidotationEditForm extends GenericEditForm<SgediRccidotation, Integer> {
    @Inject
    protected SgediRccidotationController sgediRccidotationController;
    @Inject
    protected SgedircciController sgedircciController;
    protected GenericToOneAssociation<Sgedircci, Integer> idrcci;

    @Inject
    public SgediRccidotationEditForm(SgediRccidotationRepository sgediRccidotationRepository, SgediRccidotationGraphLoader sgediRccidotationGraphLoader) {
        super(sgediRccidotationRepository, sgediRccidotationGraphLoader);
        this.setModule("DOT");
    }

    /**
     * The entity to edit/view.
     */
    public SgediRccidotation getSgediRccidotation() {
        return getEntity();
    }

    public String print() {
        return sgediRccidotationController.print(getSgediRccidotation());
    }

    @PostConstruct
    void setupIdrcciActions() {
        idrcci = new GenericToOneAssociation<Sgedircci, Integer>(sgedircciController, SgediRccidotation_.idrcci) {
            @Override
            protected Sgedircci get() {
                return getSgediRccidotation().getIdrcci();
            }

            @Override
            protected void set(Sgedircci sgedircci) {
                getSgediRccidotation().setIdrcci(sgedircci);
            }

            @NotNull
            @Override
            public Sgedircci getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Sgedircci, Integer> getIdrcci() {
        return idrcci;
    }
}
