/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.printer.SgedirffiPrinter;
import ma.sgma.edi2.repository.SgedirffiRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgedirffiPermission;

/**
 * Stateless controller for {@link Sgedirffi} conversation start.
 */
@Named
@Singleton
public class SgedirffiController extends GenericController<Sgedirffi, Integer> {
    public static final String SGEDIRFFI_EDIT_URI = "/domain/sgedirffiEdit.faces";
    public static final String SGEDIRFFI_SELECT_URI = "/domain/sgedirffiSelect.faces";

    @Inject
    public SgedirffiController(SgedirffiRepository sgedirffiRepository, SgedirffiPermission sgedirffiPermission, SgedirffiPrinter sgedirffiPrinter) {
        super(sgedirffiRepository, sgedirffiPermission, sgedirffiPrinter, SGEDIRFFI_SELECT_URI, SGEDIRFFI_EDIT_URI);
    }
}