/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediEdircciMo;
import ma.sgma.edi2.printer.SgediEdircciMoPrinter;
import ma.sgma.edi2.repository.SgediEdircciMoRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgediEdircciMoPermission;

/**
 * Stateless controller for {@link SgediEdircciMo} conversation start.
 */
@Named
@Singleton
public class SgediEdircciMoController extends GenericController<SgediEdircciMo, Integer> {
    public static final String SGEDIEDIRCCIMO_EDIT_URI = "/domain/sgediEdircciMoEdit.faces";
    public static final String SGEDIEDIRCCIMO_SELECT_URI = "/domain/sgediEdircciMoSelect.faces";

    @Inject
    public SgediEdircciMoController(SgediEdircciMoRepository sgediEdircciMoRepository, SgediEdircciMoPermission sgediEdircciMoPermission,
            SgediEdircciMoPrinter sgediEdircciMoPrinter) {
        super(sgediEdircciMoRepository, sgediEdircciMoPermission, sgediEdircciMoPrinter, SGEDIEDIRCCIMO_SELECT_URI, SGEDIEDIRCCIMO_EDIT_URI);
    }
}