/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgediEdircciMo;
import ma.sgma.edi2.domain.SgediEdircciMo_;
import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.web.domain.support.GenericSearchForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link SgediEdircciMo}.
 * It exposes a {@link SgediEdircciMo} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class SgediEdircciMoSearchForm extends GenericSearchForm<SgediEdircciMo, Integer, SgediEdircciMoSearchForm> {
    private static final long serialVersionUID = 1L;
    protected SgediEdircciMo sgediEdircciMo = new SgediEdircciMo();
    protected PropertySelector<SgediEdircciMo, String> mouvrageSelector = newPropertySelector(SgediEdircciMo_.mouvrage);
    protected PropertySelector<SgediEdircciMo, Sgedircci> idrcciSelector = newPropertySelector(SgediEdircciMo_.idrcci);

    public SgediEdircciMo getSgediEdircciMo() {
        return sgediEdircciMo;
    }

    @Override
    protected SgediEdircciMo getEntity() {
        return getSgediEdircciMo();
    }

    @Override
    public SgediEdircciMoSearchForm newInstance() {
        return new SgediEdircciMoSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.fetch(SgediEdircciMo_.idrcci);
        sp.property(mouvrageSelector);
        sp.property(idrcciSelector);
        return sp;
    }

    @Override
    public void resetWithOther(SgediEdircciMoSearchForm other) {
        this.sgediEdircciMo = other.getSgediEdircciMo();
        this.mouvrageSelector = other.getMouvrageSelector();
        this.idrcciSelector = other.getIdrcciSelector();
    }

    // Property selectors
    public PropertySelector<SgediEdircciMo, String> getMouvrageSelector() {
        return mouvrageSelector;
    }

    // Relation selectors
    public PropertySelector<SgediEdircciMo, Sgedircci> getIdrcciSelector() {
        return idrcciSelector;
    }
}
