/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.printer.SgedircciPrinter;
import ma.sgma.edi2.repository.SgedircciRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.SgedircciPermission;

/**
 * Stateless controller for {@link Sgedircci} conversation start.
 */
@Named
@Singleton
public class SgedircciController extends GenericController<Sgedircci, Integer> {
    public static final String SGEDIRCCI_EDIT_URI = "/domain/sgedircciEdit.faces";
    public static final String SGEDIRCCI_SELECT_URI = "/domain/sgedircciSelect.faces";

    @Inject
    public SgedircciController(SgedircciRepository sgedircciRepository, SgedircciPermission sgedircciPermission, SgedircciPrinter sgedircciPrinter) {
        super(sgedircciRepository, sgedircciPermission, sgedircciPrinter, SGEDIRCCI_SELECT_URI, SGEDIRCCI_EDIT_URI);
    }
}