/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.SgediTitrerffi;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link SgediTitrerffi} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class SgediTitrerffiExcelExporter extends GenericExcelExporter<SgediTitrerffi> {
    @Inject
    protected SgediTitrerffiSearchForm sf;

    public SgediTitrerffiExcelExporter() {
        super("sgediTitrerffi_idrffi", "sgediTitrerffi_titre");
    }

    @Override
    protected void fillResultItem(int row, SgediTitrerffi item) {
        int col = 0;
        setEntity(row, col++, item.getIdrffi());
        setValue(row, col++, item.getTitre());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "sgediTitrerffi_idrffi", sf.getIdrffiSelector().getSelected());
        setSelector(row++, 0, "sgediTitrerffi_titre", sf.getTitreSelector());
    }
}