/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import ma.sgma.edi2.domain.Userrole;
import ma.sgma.edi2.repository.UserroleRepository;
import ma.sgma.edi2.web.domain.support.GenericLazyDataModel;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Userrole}
 */
@Named
@ConversationContextScoped
public class UserroleLazyDataModel extends GenericLazyDataModel<Userrole, Integer, UserroleSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public UserroleLazyDataModel(UserroleRepository userroleRepository, UserroleController userroleController, UserroleSearchForm userroleSearchForm,
            UserroleExcelExporter userroleExcelExporter) {
        super(userroleRepository, userroleController, userroleSearchForm, userroleExcelExporter);
        this.setModule("USERROLE");
    }
}