/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Userrole;
import ma.sgma.edi2.printer.UserrolePrinter;
import ma.sgma.edi2.repository.UserroleRepository;
import ma.sgma.edi2.web.domain.support.GenericController;
import ma.sgma.edi2.web.permission.UserrolePermission;

/**
 * Stateless controller for {@link Userrole} conversation start.
 */
@Named
@Singleton
public class UserroleController extends GenericController<Userrole, Integer> {
    public static final String USERROLE_EDIT_URI = "/domain/userroleEdit.faces";
    public static final String USERROLE_SELECT_URI = "/domain/userroleSelect.faces";

    @Inject
    public UserroleController(UserroleRepository userroleRepository, UserrolePermission userrolePermission, UserrolePrinter userrolePrinter) {
        super(userroleRepository, userrolePermission, userrolePrinter, USERROLE_SELECT_URI, USERROLE_EDIT_URI);
    }
}