/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Userrole;
import ma.sgma.edi2.repository.UserroleRepository;
import ma.sgma.edi2.web.domain.support.GenericEditForm;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Userrole}.
 */
@Named
@ConversationContextScoped
public class UserroleEditForm extends GenericEditForm<Userrole, Integer> {
    @Inject
    protected UserroleController userroleController;

    @Inject
    public UserroleEditForm(UserroleRepository userroleRepository) {
        super(userroleRepository);
        this.setModule("USERROLE");
    }

    /**
     * The entity to edit/view.
     */
    public Userrole getUserrole() {
        return getEntity();
    }

    public String print() {
        return userroleController.print(getUserrole());
    }
}
