/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package ma.sgma.edi2.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import ma.sgma.edi2.domain.Userrole;
import ma.sgma.edi2.web.domain.support.GenericExcelExporter;
import ma.sgma.edi2.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Userrole} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class UserroleExcelExporter extends GenericExcelExporter<Userrole> {
    @Inject
    protected UserroleSearchForm sf;

    public UserroleExcelExporter() {
        super("userrole_role");
    }

    @Override
    protected void fillResultItem(int row, Userrole item) {
        int col = 0;
        setValue(row, col++, item.getRole());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setTermSelector(row++, 0, "userrole_role", sf.getRoleTermSelector());

        setSelector(row++, 0, "userrole_role", sf.getRoleSelector());
    }
}