/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Auditlog;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class AuditlogGenerator {

    /**
     * Returns a new Auditlog instance filled with random values.
     */
    public Auditlog getAuditlog() {
        Auditlog auditlog = new Auditlog();

        // simple attributes follows
        auditlog.setAuthor("a");
        auditlog.setEvent("a");
        auditlog.setEventDate(new Date());
        auditlog.setStringAttribute1("a");
        auditlog.setStringAttribute2("a");
        auditlog.setStringAttribute3("a");
        return auditlog;
    }

}