/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgedirffiErrors;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgedirffiErrorsGenerator {

    /**
     * Returns a new SgedirffiErrors instance filled with random values.
     */
    public SgedirffiErrors getSgedirffiErrors() {
        SgedirffiErrors sgedirffiErrors = new SgedirffiErrors();

        // simple attributes follows
        sgedirffiErrors.setPropriete("a");
        sgedirffiErrors.setMotif("a");
        sgedirffiErrors.setValueError("a");
        return sgedirffiErrors;
    }

}