/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import ma.sgma.edi2.domain.SgediParams;

/**
 * Integration test on SgediParamsRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgediParamsRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgediParamsRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgediParamsRepository sgediParamsRepository;

    @Inject
    private SgediParamsGenerator sgediParamsGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SgediParams sgediParams = sgediParamsGenerator.getSgediParams();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgediParams> set = newHashSet(sgediParams, sgediParams);
        assertThat(set).hasSize(1);

        sgediParamsRepository.save(sgediParams);
        entityManager.flush();

        // reload it from cache and check equality
        SgediParams model = new SgediParams();
        model.setId(sgediParams.getId());
        assertThat(sgediParams).isEqualTo(sgediParamsRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgediParams.getId()).isEqualTo(sgediParamsRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgediParams).isNotEqualTo(sgediParamsRepository.get(model));
    }

}