/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediEdircciMo;
import ma.sgma.edi2.domain.Sgedircci;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgediEdircciMoGenerator {

    /**
     * Returns a new SgediEdircciMo instance filled with random values.
     */
    public SgediEdircciMo getSgediEdircciMo() {
        SgediEdircciMo sgediEdircciMo = new SgediEdircciMo();

        // simple attributes follows
        sgediEdircciMo.setMouvrage("a");
        // mandatory relation
        Sgedircci idrcci = sgedircciGenerator.getSgedircci();
        sgedircciRepository.save(idrcci);
        sgediEdircciMo.setIdrcci(idrcci);
        return sgediEdircciMo;
    }

    @Inject
    private SgedircciRepository sgedircciRepository;
    @Inject
    private SgedircciGenerator sgedircciGenerator;
}