/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.Sgedircci;
import ma.sgma.edi2.domain.Sgedircci_;

/**
 * Integration test on SgedircciRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgedircciRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgedircciRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgedircciRepository sgedircciRepository;

    @Inject
    private SgedircciGenerator sgedircciGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Sgedircci sgedircci = sgedircciGenerator.getSgedircci();

        // add it to a Set before saving (force equals/hashcode)
        Set<Sgedircci> set = newHashSet(sgedircci, sgedircci);
        assertThat(set).hasSize(1);

        sgedircciRepository.save(sgedircci);
        entityManager.flush();

        // reload it from cache and check equality
        Sgedircci model = new Sgedircci();
        model.setId(sgedircci.getId());
        assertThat(sgedircci).isEqualTo(sgedircciRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgedircci.getId()).isEqualTo(sgedircciRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgedircci).isNotEqualTo(sgedircciRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        Sgedircci sgedircci = sgedircciGenerator.getSgedircci();

        // add it to a Set before saving (force equals/hashcode)
        Set<Sgedircci> set = newHashSet(sgedircci, sgedircci);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sgedircci.setCodeErr(null);

        sgedircciRepository.save(sgedircci);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(Sgedircci_.codeErr, (Object) null);

        List<Sgedircci> elements = sgedircciRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (Sgedircci element : elements) {
            assertThat(element.getCodeErr()).isNull();
        }
    }
}