/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import ma.sgma.edi2.domain.SgediDictodc;

/**
 * Integration test on SgediDictodcRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgediDictodcRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgediDictodcRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgediDictodcRepository sgediDictodcRepository;

    @Inject
    private SgediDictodcGenerator sgediDictodcGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SgediDictodc sgediDictodc = sgediDictodcGenerator.getSgediDictodc();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgediDictodc> set = newHashSet(sgediDictodc, sgediDictodc);
        assertThat(set).hasSize(1);

        sgediDictodcRepository.save(sgediDictodc);
        entityManager.flush();

        // reload it from cache and check equality
        SgediDictodc model = new SgediDictodc();
        model.setId(sgediDictodc.getId());
        assertThat(sgediDictodc).isEqualTo(sgediDictodcRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgediDictodc.getId()).isEqualTo(sgediDictodcRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgediDictodc).isNotEqualTo(sgediDictodcRepository.get(model));
    }

}