/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgediTitrerffi;
import ma.sgma.edi2.domain.SgediTitrerffi_;

/**
 * Integration test on SgediTitrerffiRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgediTitrerffiRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgediTitrerffiRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgediTitrerffiRepository sgediTitrerffiRepository;

    @Inject
    private SgediTitrerffiGenerator sgediTitrerffiGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SgediTitrerffi sgediTitrerffi = sgediTitrerffiGenerator.getSgediTitrerffi();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgediTitrerffi> set = newHashSet(sgediTitrerffi, sgediTitrerffi);
        assertThat(set).hasSize(1);

        sgediTitrerffiRepository.save(sgediTitrerffi);
        entityManager.flush();

        // reload it from cache and check equality
        SgediTitrerffi model = new SgediTitrerffi();
        model.setId(sgediTitrerffi.getId());
        assertThat(sgediTitrerffi).isEqualTo(sgediTitrerffiRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgediTitrerffi.getId()).isEqualTo(sgediTitrerffiRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgediTitrerffi).isNotEqualTo(sgediTitrerffiRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        SgediTitrerffi sgediTitrerffi = sgediTitrerffiGenerator.getSgediTitrerffi();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgediTitrerffi> set = newHashSet(sgediTitrerffi, sgediTitrerffi);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sgediTitrerffi.setIdrffi(null);

        sgediTitrerffiRepository.save(sgediTitrerffi);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(SgediTitrerffi_.idrffi, (Object) null);

        List<SgediTitrerffi> elements = sgediTitrerffiRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (SgediTitrerffi element : elements) {
            assertThat(element.getIdrffi()).isNull();
        }
    }
}