/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.SgedirffiErrors;
import ma.sgma.edi2.domain.SgedirffiErrors_;

/**
 * Integration test on SgedirffiErrorsRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgedirffiErrorsRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgedirffiErrorsRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgedirffiErrorsRepository sgedirffiErrorsRepository;

    @Inject
    private SgedirffiErrorsGenerator sgedirffiErrorsGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        SgedirffiErrors sgedirffiErrors = sgedirffiErrorsGenerator.getSgedirffiErrors();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgedirffiErrors> set = newHashSet(sgedirffiErrors, sgedirffiErrors);
        assertThat(set).hasSize(1);

        sgedirffiErrorsRepository.save(sgedirffiErrors);
        entityManager.flush();

        // reload it from cache and check equality
        SgedirffiErrors model = new SgedirffiErrors();
        model.setId(sgedirffiErrors.getId());
        assertThat(sgedirffiErrors).isEqualTo(sgedirffiErrorsRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgedirffiErrors.getId()).isEqualTo(sgedirffiErrorsRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgedirffiErrors).isNotEqualTo(sgedirffiErrorsRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        SgedirffiErrors sgedirffiErrors = sgedirffiErrorsGenerator.getSgedirffiErrors();

        // add it to a Set before saving (force equals/hashcode)
        Set<SgedirffiErrors> set = newHashSet(sgedirffiErrors, sgedirffiErrors);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sgedirffiErrors.setCoderffi(null);

        sgedirffiErrorsRepository.save(sgedirffiErrors);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(SgedirffiErrors_.coderffi, (Object) null);

        List<SgedirffiErrors> elements = sgedirffiErrorsRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (SgedirffiErrors element : elements) {
            assertThat(element.getCoderffi()).isNull();
        }
    }
}