/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediTitrerffi;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgediTitrerffiGenerator {

    /**
     * Returns a new SgediTitrerffi instance filled with random values.
     */
    public SgediTitrerffi getSgediTitrerffi() {
        SgediTitrerffi sgediTitrerffi = new SgediTitrerffi();

        // simple attributes follows
        sgediTitrerffi.setTitre("a");
        return sgediTitrerffi;
    }

}