/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.SearchParameters;

import ma.sgma.edi2.domain.Sgedirffi;
import ma.sgma.edi2.domain.Sgedirffi_;

/**
 * Integration test on SgedirffiRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class SgedirffiRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(SgedirffiRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private SgedirffiRepository sgedirffiRepository;

    @Inject
    private SgedirffiGenerator sgedirffiGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Sgedirffi sgedirffi = sgedirffiGenerator.getSgedirffi();

        // add it to a Set before saving (force equals/hashcode)
        Set<Sgedirffi> set = newHashSet(sgedirffi, sgedirffi);
        assertThat(set).hasSize(1);

        sgedirffiRepository.save(sgedirffi);
        entityManager.flush();

        // reload it from cache and check equality
        Sgedirffi model = new Sgedirffi();
        model.setId(sgedirffi.getId());
        assertThat(sgedirffi).isEqualTo(sgedirffiRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(sgedirffi.getId()).isEqualTo(sgedirffiRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(sgedirffi).isNotEqualTo(sgedirffiRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        Sgedirffi sgedirffi = sgedirffiGenerator.getSgedirffi();

        // add it to a Set before saving (force equals/hashcode)
        Set<Sgedirffi> set = newHashSet(sgedirffi, sgedirffi);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        sgedirffi.setStatutEch(null);

        sgedirffiRepository.save(sgedirffi);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(Sgedirffi_.statutEch, (Object) null);

        List<Sgedirffi> elements = sgedirffiRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (Sgedirffi element : elements) {
            assertThat(element.getStatutEch()).isNull();
        }
    }
}