/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import java.util.Date;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.Sgedixml;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgedixmlGenerator {

    /**
     * Returns a new Sgedixml instance filled with random values.
     */
    public Sgedixml getSgedixml() {
        Sgedixml sgedixml = new Sgedixml();

        // simple attributes follows
        sgedixml.setXml("a");
        sgedixml.setSens(1);
        sgedixml.setTyp("a");
        sgedixml.setAnne(1);
        sgedixml.setMois(1);
        sgedixml.setDecade(1);
        sgedixml.setDateGen(new Date());
        return sgedixml;
    }

}