/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediDictodc;
import ma.sgma.edi2.domain.Sgedirffi;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgedirffiGenerator {

    /**
     * Returns a new Sgedirffi instance filled with random values.
     */
    public Sgedirffi getSgedirffi() {
        Sgedirffi sgedirffi = new Sgedirffi();

        // simple attributes follows
        sgedirffi.setCodeLigne("a");
        sgedirffi.setCodeBanque("a");
        sgedirffi.setNumeroGuichet("a");
        sgedirffi.setAnneRffi("a");
        sgedirffi.setMoisRffi("a");
        sgedirffi.setDecadeRffi("a");
        sgedirffi.setBicSwift("a");
        sgedirffi.setNcp("a");
        sgedirffi.setNomRsociale("a");
        sgedirffi.setNumIdentification("a");
        sgedirffi.setCentreRc("a");
        sgedirffi.setRc("a");
        sgedirffi.setPays("a");
        sgedirffi.setVille("a");
        sgedirffi.setAdresse("a");
        sgedirffi.setNomRsocialePartenaire("a");
        sgedirffi.setPaysPartenaire("a");
        sgedirffi.setCodeNoperation("a");
        sgedirffi.setPprovenanceDestination("a");
        sgedirffi.setCodeDevise("a");
        sgedirffi.setMontantDevise(1d);
        sgedirffi.setCoursApplique(1d);
        sgedirffi.setMontantApplique(1d);
        sgedirffi.setDateExecution(new Date());
        sgedirffi.setNumeroAutorisationOc("a");
        sgedirffi.setNumeroDossier("a");
        sgedirffi.setInformationOperation("a");
        sgedirffi.setChampSupp2("a");
        sgedirffi.setChampSupp3("a");
        sgedirffi.setChampSupp4("a");
        sgedirffi.setChampSupp5("a");
        sgedirffi.setCreationDate(new Date());
        sgedirffi.setCreationAuthor("a");
        sgedirffi.setLastModificationDate(new Date());
        sgedirffi.setLastModificationAuthor("a");
        sgedirffi.setCodeErr(1);
        sgedirffi.setMotif("a");
        sgedirffi.setProperties("a");
        sgedirffi.setValeurErr("a");
        sgedirffi.setLib1("a");
        sgedirffi.setLib2("a");
        sgedirffi.setLib3("a");
        sgedirffi.setNumeroFormule("a");
        sgedirffi.setClient("a");
        sgedirffi.setCodeLocalite("a");
        sgedirffi.setDateComptable(new Date());
        sgedirffi.setMotifoc("a");
        sgedirffi.setCodeerrodc("a");
        sgedirffi.setAffectprofil("a");
        sgedirffi.setDateAffect(new Date());
        // mandatory relation
        SgediDictodc categorieFormule = sgediDictodcGenerator.getSgediDictodc();
        sgediDictodcRepository.save(categorieFormule);
        sgedirffi.setCategorieFormule(categorieFormule);
        // mandatory relation
        SgediDictodc sensOperation = sgediDictodcGenerator.getSgediDictodc();
        sgediDictodcRepository.save(sensOperation);
        sgedirffi.setSensOperation(sensOperation);
        return sgedirffi;
    }

    @Inject
    private SgediDictodcRepository sgediDictodcRepository;
    @Inject
    private SgediDictodcGenerator sgediDictodcGenerator;
}