/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import ma.sgma.edi2.domain.SgediDictodc;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class SgediDictodcGenerator {

    /**
     * Returns a new SgediDictodc instance filled with random values.
     */
    public SgediDictodc getSgediDictodc() {
        SgediDictodc sgediDictodc = new SgediDictodc();

        // simple attributes follows
        sgediDictodc.setCode(1);
        sgediDictodc.setLibelle("a");
        sgediDictodc.setLib1("a");
        sgediDictodc.setLib2("a");
        sgediDictodc.setLib3("a");
        return sgediDictodc;
    }

}