/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/audit/AuditLogListener.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.audit;

import static com.google.common.collect.Lists.newArrayList;
import static ma.sgma.edi2.service.AuditEvent.Creation;
import static ma.sgma.edi2.service.AuditEvent.Deletion;
import static ma.sgma.edi2.service.AuditEvent.Modification;

import java.util.Date;
import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;

import org.hibernate.action.spi.AfterTransactionCompletionProcess;
import org.hibernate.engine.spi.SessionImplementor;
import org.hibernate.event.spi.AbstractEvent;
import org.hibernate.event.spi.PostDeleteEvent;
import org.hibernate.event.spi.PostDeleteEventListener;
import org.hibernate.event.spi.PostInsertEvent;
import org.hibernate.event.spi.PostInsertEventListener;
import org.hibernate.event.spi.PreUpdateEvent;
import org.hibernate.event.spi.PreUpdateEventListener;
import org.hibernate.persister.entity.EntityPersister;

import com.jaxio.jpa.querybyexample.Identifiable;

import ma.sgma.edi2.context.UserContext;
import ma.sgma.edi2.domain.Auditlog;
import ma.sgma.edi2.service.AuditEvent;
import ma.sgma.edi2.service.AuditLogService;

@Named
public class AuditLogListener implements PreUpdateEventListener, PostDeleteEventListener, PostInsertEventListener {
    private static final long serialVersionUID = 1L;
    @Inject
    private AuditLogService auditLogService;
    protected List<String> skipProperties = newArrayList("version", "lastModificationAuthor", "lastModificationDate", "creationDate", "creationAuthor");
    protected List<String> skipClasses = newArrayList("Auditlog");

    protected void skipClasses(Class<?>... classesToBeIgnored) {
        for (Class<?> classToBeIgnored : classesToBeIgnored) {
            skipClasses.add(classToBeIgnored.getSimpleName());
        }
    }

    @Override
    public void onPostDelete(PostDeleteEvent event) {
        audit(event, Deletion, event.getEntity());
    }

    @Override
    public void onPostInsert(PostInsertEvent event) {
        audit(event, Creation, event.getEntity());
    }

    @Override
    public boolean onPreUpdate(PreUpdateEvent event) {
        String updateMessage = buildUpdateMessage(event);
        if (!updateMessage.isEmpty()) {
            audit(event, Modification, event.getEntity(), updateMessage);
        }
        return false;
    }

    @Override
    public boolean requiresPostCommitHanding(EntityPersister entityPersister) {
        return false;
    }

    private String buildUpdateMessage(PreUpdateEvent event) {
        String[] propertyNames = event.getPersister().getEntityMetamodel().getPropertyNames();
        Object[] oldStates = event.getOldState();
        Object[] newStates = event.getState();
        int index = 0;
        StringBuilder message = new StringBuilder(128);
        for (String propertyName : propertyNames) {
            message.append(message(propertyName, oldStates[index], newStates[index]));
            index++;
        }
        return message.toString();
    }

    private String message(String propertyName, Object oldState, Object newState) {
        if (newState instanceof Identifiable) {
            // no need to track objects
            return "";
        } else if (skipProperties.contains(propertyName)) {
            // no need to track version and lastModificationDates as they add no value
            return "";
        } else if (oldState == null && newState == null) {
            return "";
        } else if (oldState == null && newState != null) {
            return propertyName + " set to [" + newState + "]\n";
        } else if (oldState != null && newState == null) {
            return propertyName + " reseted to null\n";
        } else if (!oldState.toString().equals(newState.toString())) {
            return propertyName + " changed from [" + oldState.toString() + "] to [" + newState.toString() + "]\n";
        } else {
            return "";
        }
    }

    private void audit(AbstractEvent hibernateEvent, AuditEvent auditEvent, Object object) {
        audit(hibernateEvent, auditEvent, object, null);
    }

    private void audit(AbstractEvent hibernateEvent, AuditEvent auditEvent, Object object, String attribute) {
        String className = object.getClass().getSimpleName();
        if (skipClasses.contains(className)) {
            return;
        }

        Auditlog auditlog = new Auditlog();
        auditlog.setAuthor(UserContext.getUsername());
        auditlog.setEvent(auditEvent.name());
        auditlog.setEventDate(new Date());
        auditlog.setStringAttribute1(className);
        auditlog.setStringAttribute2(((Identifiable<?>) object).getId().toString());
        auditlog.setStringAttribute3(attribute);
        audit(hibernateEvent, auditlog);
    }

    private void audit(AbstractEvent hibernateEvent, final Auditlog auditlog) {
        hibernateEvent.getSession().getActionQueue().registerProcess(new AfterTransactionCompletionProcess() {
            @Override
            public void doAfterTransactionCompletion(boolean success, SessionImplementor session) {
                if (success) {
                    auditLogService.log(auditlog);
                }
            }
        });
    }
}