/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/audit/HibernateListenerRegistration.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.audit;

import static ma.sgma.edi2.service.AuditEvent.ApplicationShutdown;
import static ma.sgma.edi2.service.AuditEvent.ApplicationStartup;
import static org.hibernate.event.spi.EventType.POST_DELETE;
import static org.hibernate.event.spi.EventType.POST_INSERT;
import static org.hibernate.event.spi.EventType.PRE_UPDATE;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.inject.Inject;
import javax.inject.Named;

import org.hibernate.SessionFactory;
import org.hibernate.event.service.spi.EventListenerRegistry;
import org.hibernate.event.spi.EventType;
import org.hibernate.internal.SessionFactoryImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Lazy;

import ma.sgma.edi2.service.AuditLogService;

@Named
@Lazy(false)
public class HibernateListenerRegistration {
    private static final Logger log = LoggerFactory.getLogger(HibernateListenerRegistration.class);

    @Inject
    private AuditLogService auditLogService;
    @Inject
    private SessionFactory sessionFactory;
    @Inject
    private AuditLogListener auditLogListener;

    @PostConstruct
    public void registerListeners() {
        register(POST_DELETE, auditLogListener);
        register(POST_INSERT, auditLogListener);
        register(PRE_UPDATE, auditLogListener);
        auditLogService.event(ApplicationStartup);
    }

    private <T> void register(EventType<T> eventType, T t) {
        EventListenerRegistry registry = ((SessionFactoryImpl) sessionFactory).getServiceRegistry().getService(EventListenerRegistry.class);
        log.info("Registering {} listener on {} events", t.getClass(), eventType);
        registry.getEventListenerGroup(eventType).appendListener(t);
    }

    @PreDestroy
    public void destroy() {
        auditLogService.event(ApplicationShutdown);
    }
}