/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/service/AuditEvent.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package ma.sgma.edi2.service;

public enum AuditEvent {
    ApplicationStartup, //
    ApplicationShutdown, //
    LoginSuccessful, //
    Creation, //
    Deletion, //
    Modification;
}